packages/ui/package.json
pnpm-lock.yaml

ui 패키지에서 공통적으로 사용할 디펜던시를 dependencies로 추가로 설치했습니다
- tailwind-merge : 충돌(중복)되는 tailwind classname들을 합쳐주는 유틸리티
- class-variance-authority : 조건부로 CSS 클래스를 조합하고, 재사용 가능한 스타일링 구성을 정의하는 경험을 향상하는 유틸리티
- clsx : 조건적인 tailwind classname들을 하나의 string으로 합쳐주는 유틸리티
close #2

[#2] chore: ui 패키지 공통 디펜던시 설치

---

docs/storybook/package.json
docs/storybook/src/tailwind.css
docs/storybook/stories/Colors.mdx
packages/config-tailwind/globals.css
packages/config-tailwind/package.json
packages/config-tailwind/tailwind.config.ts
packages/ui/package.json
packages/ui/src/lib/utils.ts
packages/ui/src/styles.css
packages/ui/tailwind.config.ts
pnpm-lock.yaml

각 경로에서 작업한 내용은 아래와 같습니다:
- packages/config-tailwind
- `globals.css`: 프로젝트 전반에서 사용하는 디자인 토큰(색상)을 css variables로 정의했습니다. `tailwind.config.ts`에서만 색상을 custom 하지 않은 이유는 mvp 이후 배포에서 dark/light 모드 지원을 위함입니다 (css 클래스에 따른 light/dark 모드)
- `tailwind.config.ts`: `globals.css`에서 정의한 색상을 tailwind 설정으로 추가했습니다. 여기서 `colors.brand.primary`, `colors.brand.secondary`가 css변수 없이 바로 hsl값으로 정의된 이유는 라이트/다크 모드에 따른 변화가 없는 색상이기 때문입니다.
- packages/ui
- `lib/utils.ts` : `tailwind-merge`와 `clsx`를 사용하여 cn 유틸리티 함수를 정의했습니다. 다른 패키지에서 `utils.ts` 경로에 접근할 떄는 `@5unwan/utils` 로 접근하면 되도록 설정했습니다.
- docs/storybook
- `Colors.mdx`: `packages/config-tailwind/tailwind.config.ts`에서 정의한 색상 토큰을 명세했습니다. Storybook의 `ColorPalette`, `ColorItem`을 사용하였습니다. (스크린샷-a)
- a
https://tailwindcss.com/docs/customizing-colors#using-css-variables
close …

[#4/ui] feat: 디자인 토큰(색상) 및 유틸리티 설정

---

.github/pull_request_template.md
apps/trainer/.eslintrc.json
apps/user/.eslintrc.json
packages/config-eslint/base.js
packages/config-eslint/next.js
packages/config-eslint/react-internal.js

- FE 팀 내 코딩 컨벤션에 명시된 룰 중에서 eslint로 설정할 수 있는 eslint rule을 추가 하였으며, 빠른 룰 적용을 위해 필요하다고 생각되는 부분만 우선적으로 rule로 추가하였습니다. 개발을 진행하면서 FE 팀 내 코딩 컨벤션에 명시된 모든 내용과 추가적으로 적용하면 좋을 rule을 차차 적용하도록 할 예정입니다. 
- trainer 및 user 패키지에서 React 관련 eslint rule을 사용할 수 있도록 각 패키지 내의 `.eslintrc.json`에 extends로 추가하였습니다.
- PR 템플릿의 title 작성 방법을 바뀐 템플릿으로 수정하였습니다.
추가된 각 룰의 목적은 아래와 같습니다. ⬇️
```typescript
{
// var 키워드 사용을 금지하고 대신 let 또는 const를 사용하도록 강제  
"no-var": "error",  
// 특정 구문 사이에 빈 줄을 강제 (여기서는 모든 이전 구문 뒤에 return 구문이 올 경우 빈 줄을 삽입)
"padding-line-between-statements": [ 
"error",
{ blankLine: "always", prev: "*", next: "return" }
],
// 코드 블록(`{}`) 앞에 항상 공백을 강제
"space-before-blocks": [2, "always"],
// 후위 및 전위 증감 연산자(++ 또는 --) 사용을 금지
"no-plusplus": "error",   
// "마법의 숫자" 사용 금지 (명확한 의미를 가지는 상수로 대체 권장), 단 배열의 인덱스는 예외로 허용 …
```

[#7/config-eslint] chore: 코딩 컨벤션에 명시된 룰 중, eslint로 설정할 수 있는 eslint rule 추가

---

.gitignore
docs/storybook/.gitignore
pnpm-lock.yaml
turbo.json

@5unwan/storybook 패키지 빌드 시 storybook build 스크립트가 실행되면서 storybook-static/* 빌드 파일이 생성됩니다. [turborepo의 storybook 가이드를](https://turbo.build/repo/docs/guides/tools/storybook) 참고하여 turborepo가 빌드를 캐싱할 수 있도록 turbo.json을 수정했습니다
.gitignore에 storybook-static/* 경로를 추가하여 git이 storybook 빌드 결과를 git이 추적하지 않도록 설정했습니다
close #14

[#14/storybook] chore: @5unwan/storybook 패키지 빌드 결과 캐싱 및 gitignore 설정

---

docs/storybook/src/tailwind.css
packages/config-tailwind/variables.css
packages/ui/src/styles.css

사용되지 않는 TailwindCSS 기본 설정 제거 및 누락된 TailwindCSS 기본 설정 추가하였습니다.
- `config-tailwind/variables.css`에 누락된 TailwindCSS 기본 설정을 추가하였습니다.
- `config-tailwind/variables.css` 모듈을 `ui`, `docs/storybook`에서 import 하여 사용하고 있으므로 불필요한 TailwindCSS 기본 설정을 제거하였습니다.
close #19

[#19/root] fix: 사용되지 않는 TailwindCSS 기본 설정 제거 및 누락된 TailwindCSS 기본 설정 추가

---

docs/storybook/stories/Input.stories.tsx
packages/ui/src/components/Input.tsx
packages/ui/src/lib/utils.ts

- 피그마에 나와있는 Input은 위 이미지 외에도 여러가지가 있지만(with icon, with label 등) `Atmoic`한 컴포넌트 구현을 위헤 현재 PR에서는 단일 Input 컴포넌트만 구현하였습니다.
- 하나의 컴포넌트에서 모든 상황을 대응하다보면 컴포넌트의 크기가 커지고 props가 많아져 복잡할 것이라고 예상이되며, 하나의 컴포넌트에서 모든 상황을 대응하는 것이 아닌, 컴포넌트 분리를 통해 좀 더 높은 직관성을 가져가기 위함입니다.
- `with icon`, `with label`등 input을 활용하는 공통 컴포넌트는 따로 분리하여 구현하도록 할 예정입니다.
- [extendTailwindMerge github](https://github.com/dcastil/tailwind-merge/blob/main/docs/api-reference.md#extendtailwindmerge), [extendTailwindMerge 적용한 블로그](https://happynet-fe.tistory.com/1)를 참고하여 기존의 twMerge를 사용하던 `packages/ui` 내부의 `utils.ts` 함수를 수정하였습니다.
- 간단하게 말씀을 드리면 `extendTailwindMerge`를 사용하여 기존에 `twMerge`만 사용했을 때 특정 스타일이 충돌하여 먼저 작성된 특정 스타일이 제거되지 않고 병합이 될 수 있도록 작성한 것입니다. twMerge의 기능은 그대로 확장됩니다.
close #18

[#18/ui] feat: Input 공통 컴포넌트 구현

---

.husky/prepare-commit-msg
commitlint.config.cjs

> 적용할 commit, 브랜치 정책은 다음과 같습니다
- JIRA 연동 후 커밋 메세지 형식
```
[JIRA 티켓] [커밋 type]: [커밋 내용]
```
- JIRA 연동을 위한 브랜치 형식
```
[JIRA 티켓]/[커밋 type]/[작업위치]
```
- husky의 prepare-commit-msg를 활용하여 git commit 실행마다 브랜치에서 JIRA 티켓을 parsing하여 commit마다 prefix로 추가합니다.
- parsing 로직은 아래와 같습니다 (단계별 예시는 line마다 주석에서 확인 가능합니다):
``` bash
BRANCH_NAME=$(git symbolic-ref -q HEAD)  # refs/heads/PRIZ-31/chore/root
BRANCH_NAME=$(echo "$BRANCH_NAME" | awk -F'/' '{print $(NF-2)"/"$(NF-1)"/"$NF}')   # PRIZ-31/chore/root
ISSUE_TICKET=$(echo "$BRANCH_NAME" | sed -n 's/^\([A-Z]*-[0-9]*\)\/\(.*\)$/\1/p')    # PRIZ-31
```
- 이후 husky의 commit-msg 훅이 실행되는데, commitlint.config.cjs에 정의한 규칙으로 commitlint를 실행합니다.
- [commit conventions](https://www.conventionalcommits.org/en/v1.0.0/)에서 제시한 형식이 아닌 custom 키워드 ticket을 추가한 git message 형식을 사용하기 위해 …

[PRIZ-31/root] chore: JIRA 연동 설정

---

docs/storybook/stories/Dialog.stories.tsx
packages/config-tailwind/package.json
packages/config-tailwind/tailwind.config.ts
packages/ui/package.json
packages/ui/src/components/Dialog.tsx
pnpm-lock.yaml

radix-ui/react-dialog를 사용하여 Dialog 공통 컴포넌트를 구현했습니다.
- Dialog의 구성은 다음과 같습니다
``` typescript
<Dialog>
<DialogTrigger>Open</DialogTrigger>
<DialogContent>
<DialogHeader>
<DialogTitle>트레이너에게 연동 요청 중입니다</DialogTitle>
<DialogDescription>
연동 승인 시 본 서비스를 이용하실 수 있습니다
</DialogDescription>
</DialogHeader>
<DialogFooter>
<DialogClose>
<button className="border border-white">확인</button>
</DialogClose>
</DialogFooter>
</DialogContent>
</Dialog>
```
- radix-ui/react-dialog의 기능 수정 없이 구성 컴포넌트만 확장하고, 서비스 디자인을 적용했습니다. 
- 각 구성 컴포넌트의 props는 [radix API 명세서](https://www.radix-ui.com/primitives/docs/components/dialog#api-reference)에서 참고하실 수 있습니다
- 서비스 디자인을 고려하여 구성 컴포넌트 간 간격 (DialogHeader, children, DialogFooter 간 간격)조정이 쉬워지도록 DialogHeader, DialogFooter를 정의하였습니다 
- 서비스 내 Dialog의 종류는 1가지이며, Dialog의 UI를 결정하는 props가 …

[PRIZ-39/ui] feat: Dialog 컴포넌트 구현

---

package.json

turbo template에서 최신화되지 않았던 pnpm 버전을 9.15.3으로 업데이트합니다
- corepack을 활성화하여 package.json의 packageManager 옵션에 프로젝트에서 사용하는 pnpm 버전을 지정했습니다
> corepack이 활성화되지 않은 로컬 환경에서는 package.json packageManager가 적용되지 않습니다. [공식문서](https://pnpm.io/ko/9.x/installation#corepack-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)를 참고하여 **corepack이 활성화되지 않은 FE 작업자는 활성화 부탁드립니다**.

[FLIZ-5/root] chore: pnpm 버전 업데이트

---

docs/storybook/package.json
docs/storybook/stories/Switch.stories.tsx
docs/storybook/tsconfig.json
packages/ui/package.json
packages/ui/src/components/Switch.tsx
pnpm-lock.yaml

radix-ui/react-switch 를 사용하여 Switch 공통 컴포넌트를 구현했습니다.
Switch는 제어 / 비제어 방식으로 사용할 수 있습니다.
- 제어 방식
- 상위 레벨의 제어 상태를 전달받아 switch의 상태를 나타내고, 상태 핸들러를 전달받아 switch의 상태를 조작합니다
- 제어 방식 사용 시 `checked`와 `onCheckedChange` props를 사용합니다
- 비제어 방식
- 상위 레벨에서 state을 주입하지 않고, Switch 내부적으로 상태를 제어합니다
- `defaultChecked`: 비제어 Switch의 기본 상태를 지정할 수 있습니다
- `onCheckedChange`: Switch 상태 변경 시 호출되는 콜백입니다
- `name`: form 안에 switch를 사용할 경우 formData의 name을 지정합니다
- `value`: form 안에 switch를 사용할 경우 formData의 value를 지정합니다
- `disabled` : Switch의 disabled 여부를 결정합니다
- radix-ui/react-switch에서 분리되어 있는 Root과 Thumb을 하나의 컴포넌트로 통합했습니다. Switch 컴포넌트는 react-switch의 Root 가 제공하는 API를 제공합니다. API 명세는 [공식문서](https://www.radix-ui.com/primitives/docs/components/switch#api-reference) 참고 부탁드립니다

[PRIZ-41/ui] feat: Switch 컴포넌트 구현

---

docs/storybook/package.json
docs/storybook/stories/ToggleGroup.stories.tsx
packages/ui/package.json
packages/ui/src/components/ToggleGroup.tsx
pnpm-lock.yaml

radix-ui/react-toggle-group을 사용하여 ToggleGroup 공통 컴포넌트를 구현했습니다.
- ToggleGroup의 구성은 다음과 같습니다
```typescript
<ToggleGroup>
<ToggleGroupItem value="a">A</ToggleGroupItem>
<ToggleGroupItem value="b">B</ToggleGroupItem>
<ToggleGroupItem value="c">C</ToggleGroupItem>
</ToggleGroup>
```
- 리액트 Context를 활용하여 ToggleGroupItem들을 context provider로 감싸 Item 간 variant 값 (컴포넌트 디자인 결정 prop)을 통일했습니다. 
- 구성 컴포넌트의 API 명세는 [radix 공식문서](https://www.radix-ui.com/primitives/docs/components/toggle-group#api-reference)에서 확인할 수 있습니다
- 제어 방식
- 상위 레벨의 제어 상태를 전달받아 ToggleGroup의 상태 (`value`)를 나타내고, 상태 핸들러 (`onValueChange`)를 전달받아 switch의 상태를 조작합니다
- value는 ToggleGroup의 type값에 ('single' | 'multiple') 따라 string 또는 string[] 타입입니다.

[FLIZ-11/ui] feat: ToggleGroup 컴포넌트 구현

---

docs/storybook/stories/Carousel.stories.tsx
packages/ui/package.json
packages/ui/src/components/Carousel.tsx
pnpm-lock.yaml

[Embla Carousel](https://www.embla-carousel.com/)를 사용하여 Carousel 공통 컴포넌트를 구현했습니다. 
``` typescript
<Carousel>
<CarouselContent>
<CarouselItem>...</CarouselItem>
<CarouselItem>...</CarouselItem>
<CarouselItem>...</CarouselItem>
</CarouselContent>
<CarouselPrevious />
<CarouselNext />
</Carousel>
```
- Carousel
- `opts` : Embla Carousel을 커스터마이징할 수 있는 설정을 지정할 수 있습니다. Options API 명세는 [공식문서에서](https://www.embla-carousel.com/api/options/) 확인하실 수 있습니다
- `plugins` : Embla Carousel에서 제공하는 plugin을 지정하여 Carousel의 기능을 확장할 수 있습니다. Plugins에 대한 설명은 [공식문서](https://www.embla-carousel.com/api/plugins/)에서 확인하실 수 있습니다
- `orientation` : Carousel의 방향을 지정합니다. (`vertical` | `horizontal`)
- `setApi` : 리액트 state과 setApi를 활용하여 carousel API 인스턴스를 참조할 수 있습니다. 제어 상태를 사용할 때 사용하며 아래 예시와 같이 사용할 수 있습니다
``` typescript …
```

[FLIZ-23/ui] feat: Carousel 컴포넌트 구현

---

docs/storybook/package.json
docs/storybook/stories/DayofWeekPicker.stories.tsx
packages/ui/src/components/DayOfWeekPicker.tsx
packages/ui/src/components/DayOfWeekPicker/Context.tsx
packages/ui/src/components/DayOfWeekPicker/DayOfWeekPicker.tsx
packages/ui/src/components/DayOfWeekPicker/Days.ts
packages/ui/src/hooks/useDayOfWeekPickerContext.ts
pnpm-lock.yaml

DayOfWeekPicker 공통 컴포넌트를 구현했습니다
- 컴포넌트 용도 : 트레이너 도메인>PT수업시간 과 회원 도메인>PT희망시간 에서 요일 별로 공통된 비즈니스 로직을 수행하고, 각 요일의 수행 여부를 파악하기 위해 공통 컴포넌트로 구현했습니다
- DayOfWeekPicker는 요일을 선택하고, 요일별로 비즈니스 로직을 수행했는지를 파악만 하며, 요일별 비즈니스 로직 상태 및 제어 상태는 DayOfWeekPicker 상위 컴포넌트에서 별도로 관리합니다
- Anatomy 
- DayOfWeekPickerContext.Provider : DayOfWeekPicker 내부에서 공유하는 상태 (value, completed, onItemClick)를 리액트 Context에 주입합니다
- DayOfWeekPickerImpl : 실제 DayOfWeekPicker의 구현(DOM으로 나타나는 부분)
- DayOfWeekPickerItem : DayOfWeekPicker에서 선택할 수 있는 각 항목
- API Reference
- DayOfWeekPicker
- currentDay : 제어 상태, onCurrentDayChange와 함께 사용합니다. 현재 선택한 요일을 나타냅니다
- onCurrentDayChange: DayOfWeekPicker의 상태 변경 시 호출되는 콜백함수입니다
- defaultDay : 비제어 상태에서 사용되는 기본값. DayOfWeekPicker의 선택 요일의 기본값을 지정합니다
- completed : 제어 상태. [월, ... 일] 까지 요일별 비즈니스 로직 완료 여부를 …

[FLIZ-13/ui] feat: DayOfWeekPicker 구현

---

docs/storybook/stories/Button.stories.tsx
docs/storybook/stories/DayofWeekPicker.stories.tsx
packages/ui/package.json
packages/ui/src/components/Button.tsx
packages/ui/src/components/DayOfWeekPicker/index.tsx
packages/ui/src/hooks/useDayOfWeekPickerContext.ts
pnpm-lock.yaml

@radix-ui/react-slot을 사용하여 Button 공통 컴포넌트를 구현했습니다
- `variant:` 버튼 종류(주로 색상)를 지정할 수 있습니다. 
- `size:` 버튼의 크기를 (높이, padding, 글씨 크기) 지정할 수 있습니다.

[FLIZ-24/ui] feat: Button 컴포넌트 구현

---

docs/storybook/stories/TimePicker.stories.tsx
packages/config-tailwind/tailwind.config.ts
packages/config-tailwind/variables.css
packages/ui/package.json
packages/ui/src/components/TimePicker.tsx
pnpm-lock.yaml

- keen-slider 오픈소스 라이브러리를 바탕으로 TimePicker 공통 컴포넌트를 구현하였습니다.
- [keen-slider TimePicker 컴포넌트 레퍼런스](https://codesandbox.io/p/sandbox/great-hermann-9xglw8?file=/src/Wheel.tsx)
- [keen-slider API 레퍼런스](https://keen-slider.io/docs#properties)
- Interface
```ts
type TimePickerProps = {
startNumber?: number; // 기본값이 0 이며, 이 값부터 슬라이더의 숫자가 시작됨
initIdx?: number; // 슬라이더의 초기 선택 위치 선정
label?: string; // 슬라이더 옆에 표시되는 라벨 텍스트
length: number; // 슬라이더에 표시될 전체 항목 수
loop?: boolean; // 슬라이더의 순환 여부 결정
viewPerspective?: "left" | "right" | "center"; // 슬라이더의 3D 시점을 설정
setValue?: (relative: number, absolute: number) => string; // 슬라이더 값의 커스텀 포맷팅을 위한 함수
width: number; // 슬라이더의 너비 지정
ref: // 현재 선택된 값을 외부에서 참조하기 위한 ref
};
```
- 제어 컴포넌트 설계의 한계
- 해당 컴포넌트는 휠 슬라이드가 돌아갈 때마다 엄청난 리렌더링을 일으킵니다. 따라서 `TimePicker`에서 선택된 값을 상위에서 …

[FLIZ-18/ui] feat: TimePicker 공통 컴포넌트 구현

---

docs/storybook/stories/Spinner.stories.tsx
packages/ui/src/components/Spinner.tsx

스피너 컴포넌트를 구현하고, 스토리북을 작성하였습니다.
cva()를 통해 사이즈를 조절할 수 있으며 아래 코드와 같이 컴포넌트를 호출할 수 있습니다.
```typescript
// size: default(small)
// loading: required
<Spinner size={"small" | "middle"} loading={true | false}/>
```
> ReadOnly로 props를 주지 않으면 lint 경고가 나타나 ReadOnly를 주었더니 loading을 초기화하면 Storybook description 타입에 unknown이 발생하여 loading은 required로 설정하였습니다.
코드와 구조적으로 괜찮은지 봐주시면 감사하겠습니다.

[FLIZ-21/ui] Spinner 공통 컴포넌트 구현

---

build.sh

build.sh에서 `cd ../` 커맨드가 없어 FitLink-FE 폴더가 없는 오류를 해결하기 위해 build.sh를 수정했습니다.

[FLIZ-41/root] fix: build.sh 오류 해결

---

build.sh

Deploy pipeline의 Pushes to another repository 단계에서` ls: output: No such file or directory` 오류를 해결하기 위해 build.sh 스크립트를 수정했습니다.

[FLIZ-42/root] fix: build.sh 스크립트 수정

---

docs/storybook/stories/Drawer.stories.tsx
packages/ui/package.json
packages/ui/src/components/Drawer.tsx

`shadcn`에 정의된 `vaul`을 이용하여 notification 관련  Drawer 컴포넌트를 구현하였습니다.
유저 notification에서만 사용하는 것으로 보아, `default` `direction`을 `left`로 변경하였으며,
left만 사용할 것으로 예상되어 그 외 방향은 오히려 다른 컴포넌트가 개발이 진행되고 난 후 개발되는 것이 좋다판단하여 `left` 방향으로만 개발해놓았습니다.
해당 컴포넌트를 스토리북에서도 확인 할 수 있습니다.
사용방법은 다음과 같습니다.
```typescript
import React from "react";
import {
Drawer,
DrawerClose,
DrawerContent,
DrawerHeader,
DrawerTitle,
DrawerTrigger,
} from "./_components/Drawer";
import { X } from "lucide-react";
// 함수명은 자유롭게
function Notification() {
return (
<div>
<Drawer>
<DrawerTrigger asChild={true}>
<div>Open</div>
</DrawerTrigger>
<DrawerContent>
<DrawerHeader>
<DrawerTitle>
<div className="text-title-1 flex items-center justify-between">
알림
<DrawerClose>
<X className="relative text-[25px]" />
</DrawerClose>
</div>
</DrawerTitle> …
```

[FLIZ-19/ui] feat: Drawer 공통 컴포넌트 구현

---

packages/ui/package.json
packages/ui/src/components/Dropdown/index.tsx
packages/ui/tsconfig.json

- 위 첨부한 이미지 처럼 드랍다운 컴포넌트의 바깥을 클릭해도 드랍다운이 닫히지 않는 버그를 발견하여 드랍다운이 올바르게 동작하도록 버그를 수정하였습니다.
- handleClickOutside 함수가 isOpen을 초기 값으로 기억(클로저로 캡처)하여 제대로 드랍다운 컴포넌트가 닫히지 않는 문제로, useEffect의 의존성 배열에 isOpen을 주입하여 handleClickOutside 함수가 새로운 isOpen 상태를 기억하게 함으로써 버그를 해결하였습니다.
test-utils path alias를 ui 패키지에서 제대로 인식하지 못하는 버그가 발생하여 절대경로를 사용하는 방향으로 경로를 수정하였습니다.

[FLIZ-57/ui] fix: Dropdown 컴포넌트 바깥쪽 클릭시 닫히지 않는 버그 수정

---

apps/trainer/components/TimeOption.tsx
apps/trainer/package.json
docs/storybook/package.json
docs/storybook/stories/trainer/TimeOption.stories.tsx
docs/storybook/tailwind.config.ts
docs/storybook/vite.config.ts
pnpm-lock.yaml

해당 컴포넌트는 trainer 도메인에서 사용되는 공통 컴포넌트로 예약/일정 관리 페이지에서 특정 시간 블록을 선택했을 때 나타나는 바텀 시트에 주로 사용이되는 컴포넌트입니다.
- 해당 컴포넌트는 아이콘과 컨텐츠(텍스트)로 이루어진 컴포넌트로 상위에서 보다 자유롭게 합성하여 핸들링 할 수 있도록 합성 컴포넌트 패턴으로 설계하여 구현하였습니다.
- TimeOption 공통 컴포넌트의 스토리를 작성하였으며, 현재 figma에 정의된 네 가지 옵션에 대해 각각 정의해두었습니다.
- 해당 컴포넌트는 아직까지 view 역할만 하고 있고, 이벤트 핸들러도 상위에서 주입받고 있기 때문에 단위 테스팅은 불필요하다고 판단했습니다.
- apps/trainer 모듈에서 tailwind를 적용할 수 있게 작성하였습니다.
- apps/trainer 모듈의 컴포넌트를 스토리로 작성할 수 있게 package.json에 export를 작성하였습니다.
- docs/storybook 모듈에서 apps/trainer 모듈의 컴포넌트를 가져올 수 있도록 디펜던시를 추가하였습니다.
- docs/storybook 모듈에서 apps/trainer 모듈의 path alias를 이해할 수 있도록 vite.config를 수정하였고, apps/trainer 모듈에서 가져온 컴포넌트에 tailwind가 적용될 수 있도록 tailwind.config를 수정하였습니다.
해당 컴포넌트의 경우 내부적으로 공유되는 상태가 없어 useContext를 사용하지 않았습니다. 따라서 자식 컴포넌트들을 TimeOption에서만 사용하도록 강제할 수가 없는데, …

[FILZ-53/trainer] feat: 트레이너 도메인 TimeOption 공통 컴포넌트 구현

---

.github/workflows/test.yml
package.json
turbo.json

- 각 패키지에 작성된 테스트 코드 실행 자동화를 위해 CI/CD를 작성하였습니다.
- 루트 환경에서 재귀적으로 각 패키지들을 돌며 테스트를 실행하기 위해 루트 package.json에 스크립트를 추가하였습니다.
- turbo.json의 task에 test를 캐싱하도록 설정하여 테스트 관련 파일들이 변경되지 않는 한 캐싱된 결과가 나타나도록 작성하였습니다. 
- `dev`, `FILZ-*` 브랜치에서 PR이 생성될 경우 CI/CD가 실행됩니다.
- Settings -> Require status checks to pass before merging 설정도 추가하여 테스트가 통과되지 않을 시 Merge 할 수 없도록 수정하였습니다.
- pnpm 관련 의존성을 github action에서 캐싱하도록 하여 lock파일의 변경이 없다면 기존 pnpm 설치시간 16분 -> 55초로 단축하도록 최적화하였습니다.

[FILZ-55/root] ci: test 자동화를 위한 CI/CD 구축

---

apps/trainer/components/CalendarHintGroup.tsx
docs/storybook/stories/trainer/Calendar.stories.tsx
docs/storybook/stories/trainer/CalendarHintGroup.stories.tsx

CalendarHintGroup 컴포넌트를 구현했습니다
```tsx
<div>
{CalendarHintInfo.map(({ color, content }, idx) => (
<CalendarHint key={`${color}-${content}-${idx}`} color={color} content={content} />
))}
</div>
```
CalendarHintGroup을 구성하는 단위입니다. ui/components/Badge 컴포넌트를 사용하여 구현했습니다
- content: CalendarHint의 텍스트 내용을 지정합니다
- color: CalendarHint가 설명하는 색상을 지정합니다

[FLIZ-29/trainer] feat: CalendarHintGroup 컴포넌트 구현

---

packages/config-tailwind/tailwind.config.ts

- 디자인팀에서 변경한 `Typograph`를 반영하였으며, 기존에 잘못 작성된 `line-Height` 토큰의 단위를 `rem`으로 변경하였습니다.

[FLIZ-76/config-tailwind] chore: 변경된 Typography와 동일하게 tailwind config TypoGraphy 토큰 재정의

---

packages/ui/jest.config.js
packages/ui/src/components/__tests__/Dropdown.spec.tsx
packages/ui/src/components/__tests__/RequestStatus.spec.tsx
packages/ui/src/components/__tests__/Stepper.spec.tsx
packages/ui/src/components/__tests__/TimeCellToggleGroup.spec.tsx
packages/ui/src/hooks/__tests__/useCallbackRef.spec.tsx
packages/ui/src/hooks/__tests__/useControllableState.spec.tsx
packages/ui/src/utils/__tests__/DayPickerUtils.spec.ts
packages/ui/src/utils/__tests__/timeCellUtils.spec.ts

- 기존의 `tsconfig.json`에 작성된 path alias를 Jest에서 인식하지 못하는 문제를 `jest.config.js` 파일의 `moduleNameMapper`를 사용하여 해결하였습니다.
- 각 패키지별 테스트 환경의 `tsconfig.json`에 작성된 path alias는 `jest.config.js` 파일의 `moduleNameMapper`에도 똑같이 적용해 주어야 jest가 경로를 인식할 수 있습니다.

[FILZ-75/ui] chore: ui 패키지 테스트 파일 path alias 적용

---

apps/trainer/components/NotificationAccordion.tsx
apps/trainer/components/NotificationSideBar.tsx
docs/storybook/stories/trainer/Calendar.stories.tsx
docs/storybook/stories/trainer/NotificationSideBar.stories.tsx

- 해당 컴포넌트는 트레이너 도메인의 알림 페이지에서 햄버거 버튼 클릭시 나타나는 알림 카테고리 사이드바입니다.
- 사이드바에 나타나는 카테고리별로 클릭을 하게 되면 카테고리별 페이지로 이동하게 됩니다(아직 페이지 네이밍이 정해지지 않았기 때문에 구현 X)
- 상위 `NotificationSideBar`에서 `NotificationAccordion`을 포함하여 알림 카테고리를 나타냅니다.
- `NotificationAccordion`의 경우 확인하지 않은 알림의 개수를 API로 받아와야 하는데, BE 쪽에서 어떤식으로 데이터를 넘겨줄지 아직 나와있는 문서가 없어 더미 데이터로 먼저 작성하였습니다.
해당 컴포넌트의 스토리를 작성하였으며, 테스트의 경우 각각 이미 테스트가 검증된 Drawer, Accordion 공통 컴포넌트를 사용 하였기에 테스트 코드를 작성하지 않았습니다. 하지만 추후 비즈니스 로직을 작성하게 되면 테스트 코드를 작성할 예정입니다.

[FILZ-67/trainer] feat: 트레이너 도메인 알림 카테고리 사이드바 구현

---

docs/storybook/stories/PTHistory.stories.tsx
packages/ui/src/components/PTHistoryItem.tsx

PTHistoryItem 컴포넌트를 구현했습니다
- `reservationDate === 'NONE'` 인 경우 UI 및 상호작용 여부가 도메인 종류에 따라 구분되는 것을 고려하여 설계했습니다. 
- REST API로 주어지는 날짜 형식을 format하기 위해 `@ui/libs/DateController` 를 활용했습니다
- `try...catch`문으로 감싸 컴포넌트 렌더링 중 에러가 발생할 경우 undefined를 반환합니다
- `reservationDate`: PT 내역 날짜를 지정합니다
- `status`: PT 내역의 처리 상태를 지정합니다 (`'COMPLETED' | 'NO_SHOW' | 'NONE'`)
컴포넌트 렌더링 중 에러 발생 시 `undefined`를 반환하게 한 이유는 ListItem 하나에서 발생한 오류가 전체 List에 까지 영향을 미치지 않게 하기 위해서입니다. 각 Item을 `ErrorBoundary`로 감싸는 방법도 있겠지만, 
- 에러 발생 시, 각 Item에 대한 재요청을 제공하지 않으며 
- 사용자에게 정상적인 Item과 오류가 있는 Item을 동일한 리스트 안에 보여주는 것이 UX측면에서 안 좋다고 생각하여
해당 방식을 선택했습니다. 
에러 처리에 대한 피드백 부탁드립니다.

[FLIZ-81/ui] feat: PTHistoryItem 컴포넌트 구현

---

apps/trainer/components/PTSchedule.tsx
docs/storybook/stories/PTPreference.stories.tsx
docs/storybook/stories/trainer/PTSchedule.stories.tsx
packages/ui/src/components/PTPreference.tsx
packages/ui/src/utils/makeWeekSchedule.ts

makeWeekSchedule 유틸 모듈을 구현하고, 이를 활용하여 PTSchedule 및 PTPreference 컴포넌트를 구현했습니다
- makeWeekSchedule: `TimeBlockSchedule | TimeSpanSchedule` 타입의 인자를 받아 요일별로 연속된 시간들을 묶어 'HH:mm - HH:mm' 문자열 배열로 변환해주는 함수입니다
```tsx
type TimeBlockSchedule = {
type: "block";
schedule: {
dayOfWeek: DaysOfWeek;
preferenceTimes: string[];
}[];
};
type TimeSpanSchedule = {
type: "span";
schedule: {
dayOfWeek: DaysOfWeek;
isHoliday: boolean;
startTime: string;
endTime: string;
}[];
};
```
- PTSchedule
- PTPreference

[FLIZ-86/ui, trainer] feat: PTSchedule, PTPreference 컴포넌트 구현

---

docs/storybook/stories/Header.stories.tsx
packages/ui/src/components/Header.tsx

Header 컴포넌트를 구현했습니다
- 페이지마다 왼쪽, 오른쪽 버튼의 아이콘 및 비즈니스 로직이 달라 컴파운드 컴포넌트 패턴을 사용하여 조금 더 확장이 용이하도록 설계했습니다
```tsx
<Header>
<Header.Left>LEFT</Header.Left>.  // 또는 <Header.Back />
<Header.Title content="TITLE" />
<Header.Right>RIGHT</Header.Right>
</Header>
```
- Header : 컴포넌트의 Root. 3열 그리드 레이아웃입니다
- Left: justify-self: flex-start 인 div
- Right: justify-self: flex-right인 div
- Back: Left 대신 사용할 수 있습니다. 뒤로가기 버튼이 추가된 Left입니다

[FLIZ-80/ui] feat: Header 컴포넌트 구현

---

docs/storybook/stories/ProfileHeader.stories.tsx
packages/ui/src/components/ChevronTrigger.tsx
packages/ui/src/components/ProfileHeader.tsx

ProfileHeader 컴포넌트를 구현했습니다
- 제공해야 하는 디자인의 종류와 확장성을 고려하여 컴파운드 컴포넌트 기법을 사용했습니다
추가적으로 Chevron을 가지며 클릭 핸들러를 주입하는 div의 재사용성이 높아 ChevronTrigger 컴포넌트로 로직을 분리하였습니다
```tsx 
<ProfileHeader>
<ProfileHeader.Section
onClick={() => {
alert("clicked");
}}
>
<ProfileHeader.Avatar name="홍길동" imageSrc="https://picsum.photos/300" />
<ProfileHeader.Name name="홍길동" />
</ProfileHeader.Section>
</ProfileHeader>
```
- `ProfileHeader`: 컴포넌트의 root
- `ProflieHeader.Section`: 컴포넌트 레이아웃의 단위로 onClick 주입 시 ChevronTrigger로 wrapping됩니다
- `ProfileHeader.Avatar`: @ui/Avatar를 사용했습니다
- `ProfileHeader.Name`: @ui/Text.Title2를 사용했습니다

[FLIZ-62/ui] feat: ProfileHeader 컴포넌트 구현

---

apps/trainer/components/BottomNavigation.tsx
docs/storybook/stories/trainer/BottomNavigation.stories.tsx
docs/storybook/tailwind.config.ts

- 트레이너 도메인에서 공통으로 사용 될 바텀 네비게이션으로 `캘린더/회원/알람/마이페이지` 로 이동할 수 있습니다.
아직 정해진 페이지 네이밍이 없는 상태라 라우팅 기능 같은 핸들러는아직 작성하지 않은 상태이며, 포커싱 색상 처리는 추후 `url state`를 사용할 예정입니다.
또한 단순히 view만 보여지고 있는 형태이기 때문에 테스트는 작성하지 않았으며 스토리만 작성된 상태입니다.

[FLIZ-69/trainer] feat: 트레이너 도메인 BottomNavigation 컴포넌트 구현

---

docs/storybook/stories/Button.stories.tsx
docs/storybook/stories/Icon.stories.tsx
packages/ui/src/components/Button.tsx
packages/ui/src/components/Icon.tsx

Icon 컴포넌트를 구현한 뒤, 기존 @ui/Button 컴포넌트에 Icon 기능을 추가하였습니다.
- 프로젝트에서 모든 Lucide Icon을 사용할 시에 사용하는 제네릭한 Icon입니다
- `name`: 사용할 Lucide Icon 이름을 지정합니다
- `background`: `Icon`을 배경 circle 안에 nest하고 싶을 시에 지정합니다. 지정된 값 (`brand`, `sub1`, `sub2`, `sub3`, `sub4`, `sub5`, `notification`)을 `background-color`로 설정합니다
- `size:` Icon의 크기를 지정합니다. 지정된 값 (`sm`, `md`, `lg`, `xl`)을 LucideIcon `size` props로 설정합니다
기존 Button에 다음 기능을 추가했습니다
- `icon`, `iconRight` props로 `Button` 내 `Icon` 렌더링
- `variant`에 `secondary`, `outline`, `ghost` 추가
- `variant`에 `dark` 제거
- `size`에 `xl` 추가
- `size`에 `icon` 제거
- `corners` prop을 추가하여 `Button`의` border-radius `값 지정
- `icon` : `Icon`의 `name` props 값을 주입 시 해당 `Icon`을 `Button` `children`의 왼쪽에 렌더링합니다
- `iconRight`: `Icon`의 `name` props 값을 주입 시 해당 `Icon`을 `Button` `children`의 오른쪽에 렌더링합니다
- …

[FLIZ-88/u] feat: Icon 컴포넌트 구현 및 Button에 Icon 기능 추가

---

docs/storybook/stories/ProfileItem.stories.tsx
packages/ui/src/components/ProfileItem.tsx

사용자의 마이페이지에 표시될 프로필 아이템을 구현하였습니다.
컴포넌트의 스토리북을 작성하였습니다.
해당 컴포넌트는 회원과 트레이너 모두 사용되므로 공통 컴포넌트로 구현하였습니다.
`{children}`으로 주입하여 컴포넌트를 사용합니다.
의견 있으시면 리뷰에 남겨주시면 감사하겠습니다.
스크린샷은 figma에 사이드 공간이 있어 배경색을 통일하여 촬영하였으며,
실제 데이터에는 사이드에 margin없이 작성하였습니다.
div를 Icon, Title, Content로 나누었는데
Content는 기본 `flex text-sub2 ...`  값을 가지는데 페이지 이동에 대한 버튼이 주어지면 `text-sub3`를 주어야하는데
따로 `ContentRouter` 혹은 `ContentOption`와 같은 컴포넌트를 하나 더 넣어 사용자가 상위에서 컴포넌트를 주입할 때 **스타일링에 조금 더 신경이 덜 쓰이도록** 하면도 어떨까 하였습니다.

[FLIZ-77/feat/ui] feat: 사용자 마이페이지 ProfileItem 구현

---

apps/user/app/global.css
apps/user/app/layout.tsx
apps/user/components/BottomNavigation.tsx
apps/user/package.json
apps/user/tailwind.config.ts
packages/config-tailwind/tailwind.config.ts
packages/ui/src/components/Header.tsx
pnpm-lock.yaml

회원 도메인 기본 레이아웃 작업을 진행했습니다
레이아웃은 모바일 우선으로 설정하였습니다
- Header 컴포넌트도 layout에 추가하고 싶었으나, 페이지별로 지원해야 하는 버튼 및 로직이 달라 page 레벨에서 Header를 추가하는 방식을 선택했습니다
- 따라서 main 시멘틱 태그는 사용하지 않았으며, main 태그를 추가하고 싶은 경우, page 레벨에서 진행해야 할 것 같습니다
- Header 컴포넌트에 누락되어 있던 backgroundColor 및 height을 지정했으며 position: sticky로 설정했습니다
- BottomNavigation 컴포넌트는 position: fixed로 설정했습니다
- 회원 도메인 내 엘리먼트의 기본 box-sizing을 border-box로 설정했습니다
- RootLayout의 body 태그의 box-sizing: content-box로 지정하여 BottomNavigation이 body와 겹쳐 body의 border가 일부분 가려지는 현상을 방지했습니다
**프로젝트에서 Header를 어떻게 사용할지에 대해 의견 부탁드립니다**
- RootLayout에 Header 컴포넌트 추가
- page마다 Header를 추가할 필요가 없습니다
- 대신 Header를 client component로 변경하고 page마다 page mount 시 Header에 필요한 데이터 (button, buttonHandler, 제목)를 전역 상태나 Header Context에 주입해야 합니다
- 동적으로 렌더링을 진행해야 하기 때문에 SSR을 포기해야 합니다. 
- 다만, page …

[FLIZ-98/user] style: 회원 도메인 기본 layout 스타일링

---

packages/core/.eslintrc.js
packages/core/package.json
packages/core/src/api/core.ts
packages/core/src/api/types/common.ts
packages/core/src/utils/localStorage.ts
packages/core/tsconfig.json
pnpm-lock.yaml

- `packages/core` 모듈은 `FitLink` 프로젝트 전체에서 공통으로 사용되는 로직을 모아 놓은 모듈입니다. 
- 현재까지 해당 모듈의 예상되는 사용 용도는 아래와 같습니다.
- api 공통 로직
- 공통 util 함수
- 공통 비즈니스 로직
- 공통 interface
- 해당 파일은 axios instance를 사용하여 api 관련 로직을 중앙 관리하기 위해 추상화 한 함수로, 서버 컴포넌트와 클라이언트 컴포넌트에 모두 대응할 수 있도록 설계되었습니다.
- 각각의 상황에 NextJS 프로젝트를 사용하는 서비스에서 `Provider` 컴포넌트를 만들고 그 내부에 `initCoreApi` 함수를 호출하여 baseUrl과 token을 주입하도록 구현하였습니다.
- `initCoreApi`로 함수를 export한 이유는, `packages/core`에서 환경 변수를 세팅하여 baseUrl에 주입하고 서비스 패키지에서 core.ts를 사용할 때 환경 변수를 참조하지 못하는 이슈가 있었습니다. 이 이슈를 해결하는 방법을 아직 찾지 못하였으며, 공통 로직인 만큼 core에서 baseUrl을 고정으로 사용하기보다 core를 사용하는 서비스 패키지에서 직접 주입하도록 하는 것이 오히려 더 유연한 공통 로직이 될 수 있을 것 같아 현재와 같이 구현하였습니다.
- `initCoreApi`의 `tokenProvider`는 서버/클라이언트 컴포넌트에서 각각에 상황에 맞게 토큰을 불러와 주입할 수 있도록 설계되었습니다. core.ts에서 클라리언트 컴포넌트에서만 참조할 수 있는 localStorage를 사용하여 …

[FLIZ-108/core] feat: packages/core 모듈 생성 및 해당 모듈에 axios instance, 공통 DTO 타입 정의

---

apps/trainer/services/auth.ts
apps/trainer/services/types/auth.dto.ts
apps/user/services/types/auth.dto.ts

트레이너 > Auth 도메인의 DTO 타입 정의와 REST API 요청 함수를 정의했습니다
- 프로젝트 type 컨벤션에 따라 DTO 타입 파일은 trainer/services/types 폴더에 도메인 이름으로 생성했습니다
- 프로젝트 type 컨벤션에 따라 DTO 타입 파일은 trainer/services 폴더에 도메인 이름으로 생성했습니다
user/services/types/auth.dto.ts에서 불필요한 dto 타입을 제거했습니다

[FLIZ-131/trainer] feat: Auth DTO 및 API 작업

---

apps/trainer/services/notification.ts
apps/trainer/services/types/notification.dto.ts
apps/user/services/notification.ts

트레이너 > 알림 도메인의 DTO 타입 정의와 REST API 요청 함수를 정의했습니다
- 프로젝트 type 컨벤션에 따라 DTO 타입 파일은 trainer/services/types 폴더에 도메인 이름으로 생성했습니다
- 프로젝트 type 컨벤션에 따라 DTO 타입 파일은 trainer/services 폴더에 도메인 이름으로 생성했습니다

[FLIZ-132/trainer] feat: 알림 DTO 및 API 작업

---

apps/user/services/myInformation.ts
apps/user/services/types/myInformation.dto.ts
packages/core/src/api/types/common.ts

유저 도메인의 내 정보 관련 카테고리 DTO 타입 정의와 API 요청 함수를 정의했습니다.
- 프로젝트 type 컨벤션에 따라 DTO 타입 파일은 user/services/types 폴더에 카테고리 이름으로 생성했습니다
- 프로젝트 type 컨벤션에 따라 API 함수를 모아 놓은 파일은 user/services 폴더에 카테고리 이름으로 생성했습니다

[FILZ-133/user] feat: 유저 도메인 Member 내 정보 관련 DTO 타입 정의 및 API 함수 구현

---

apps/trainer/queries/myInformation.ts
apps/trainer/queries/notification.ts
apps/trainer/queries/reservation.ts
apps/trainer/queries/userManagement.ts
apps/trainer/services/myInformation.ts
apps/trainer/services/reservations.ts
apps/trainer/services/types/userManagement.dto.ts
apps/trainer/services/userManagement.ts

- 트레이너 도메인에서 `QueryKey Factory`의 명확한 관심사 분리를 위해 `엔티티(회원관리, 예약, 알림, 내정보)`를 기반으로 분리하여 QueryKey Factory를 작성하였습니다.
- 쿼리 키는 계층 구조로 설계되어 있고 각 계층 구조의 루트 키는 `엔티티명+BaseKeys`객체에 구현되어 있으며 각각의 쿼리는 `queryOptions`로 감싸져 `엔티티명+Quries` 객체에 구현되어있습니다. 
- 이와 같은 설계는 `Queries` 객체 내부에서 작성된 쿼리 키를 `set/getQueryData`와 같은 API에서 사용할 때 타입 세이프하게 사용할 수 있도록 강제합니다. 
- `엔티티명+BaseKeys` 객체 내부에 정의된 타입 세이프하지 않은 쿼리키를 `set/getQueryData`와 같은 API에서 오용할 수 있는 경우의 수가 존재하지만, 이 같은 경우 PR #101 에서 정해진 컨벤션을 통해 `엔티티명+BaseKeys` 객체 내부에는 Invalidate에 사용하기 위한 각 계층 구조의 루트 쿼리 키만 작성하여 `set/getQueryData`와 같은 API에서는 사용하지 않도록 합니다.
- 트레이너 도메인의 API 함수가 void를 리턴하도록 잘못 작성되어있어 이를 수정하였습니다.
- 누락된 특정 회원의 PT 내역을 조회하는 API 함수와 DTO 타입을 새로 정의하였습니다.
- 쿼리의 네이밍 피드백과 PR #101 에서 정의된 내용이 잘 반영되었는지 확인 부탁드립니다.

[FLIZ-137/trainer] feat: 트레이너 도메인 QueryKey Factory 구현

---

apps/user/app/notification/_components/Fallback.tsx
apps/user/app/notification/_components/NotificationContainer.tsx
apps/user/app/notification/_components/NotificationContent.tsx
apps/user/app/notification/_components/NotificationList.tsx
apps/user/app/notification/layout.tsx
apps/user/app/notification/page.tsx
docs/storybook/stories/Skeleton.stories.tsx
packages/core/src/api/types/common.ts
packages/ui/src/components/NotificationItem/NotificationItem.tsx
packages/ui/src/components/NotificationItem/NotificationThumbnail.tsx
packages/ui/src/components/Skeleton.tsx

회원 서비스 알림(notification) 페이지를 구현했습니다
1. Skeleton 공통 컴포넌트 구현
shadcn의 [Skeleton 컴포넌트](https://ui.shadcn.com/docs/components/skeleton)를 ui 패키지에 설치했습니다
Skeleton 공통 컴포넌트를 활용하여 notification 페이지 스켈레톤을 구현했습니다
2.  수정된 API에 맞게 notification domain DTO를 수정했습니다
3. NotificationItem 및 자식 컴포넌트의 props를 수정했습니다
optional 설정이 필요한 props에 대해 optional props로 수정했습니다
4. NotificationItem을 활용하여 페이지 UI를 설계했습니다
5. API 연결 및 Suspense 설정
API 로직을 연결했습니다. 또한 React Suspense로 비동기 작업이 있는 컴포넌트를 wrapping하여 비동기 상태에 따른 UI를 선언적으로 지정했습니다
- 예외처리의 경우 별도의 PR로 공통 ErrorBoundary를 구현할 예정입니다

[FLIZ-97/user] feat: 알림 페이지 구현

---

packages/ui/src/components/Spinner.tsx

Spinner 컴포넌트의 ref 콜백 함수가 반환하는 값의 타입이 void가 되도록 인라인 코드를 수정하였습니다.

[FLIZ-176/ui] fix: Spinner 컴포넌트의 타입에러로 인한 빌드 에러 수정

---

apps/user/tailwind.config.ts

#109 PR은 트레이너 도메인의 tailwind.config content를 수정하였는데 PR 제목과 브랜치 생성을 user로 잘못 생성하였습니다.
유저 도메인의 tailwind.config content의 불필요한 파일 스캔을 수정하여 성능 저하를 방지하였습니다.

[FLIZ-187/user] fix: 유저 도메인의 tailwind.config content의 불필요한 파일 스캔 수정

---

.github/workflows/deploy.yml

vercel을 기반으로 서비스 배포할 fork repository cicd를 변경하였습니다.
기존 yjc2021 -> choi-ik으로 변경하여 제 개인 리포지토리에 싱크가 맞춰지도록 수정하였습니다.

[FLIZ-182/root] ci: 서비스 배포 fork repository ci/cd 변경

---

build.sh

root의 build.sh에서 기존에 output 폴더를 제거하던 로직 제거하여 개인 레포지토리로 PR merge를 반영할 때 기존에 존재하던 폴더를 삭제하던 이슈 해결

[FLIZ-193/root] chore:  root의 build.sh에서 기존에 output 폴더를 제거하던 로직 제거

---

build.sh

origin 레포지토리의 모든 파일 및 폴더(dot 파일 및 숨김 파일)를 vercel을 사용하여 배포하기 위해 개인 레포로 복사하도록 build.sh 수정

[FLIZ-202/root] fix: origin 레포의 모든 파일 및 폴더를 개인 레포에 복사하도록 build.sh 수정

---

packages/ui/src/components/ProfileItem.tsx

`ProfileItem` 컴포넌트의 icon props의 타입 불일치로 발생하는 eslint 에러로 인한 빌드 에러를 수정하였습니다.

[FLIZ-203/ui] fix: ProfileItem 컴포넌트의 icon props의 타입 불일치로 발생하는 eslint 에러 수정

---

turbo.json

vercel이 터보레포의 환경 변수를 이해할 수 있도록 turbo.json의 globalEnv에 환경 변수 네이밍 추가

[FLIZ-204/root] chore: vercel이 터보레포의 환경 변수를 이해할 수 있도록 turbo.json의 globalEnv에 환경 변수 네이밍 추가

---

docs/storybook/stories/user/Calendar.stories.tsx

스토리북의 `user/Calendar` 스토리의 잘못된 import 경로를 수정하여 스토리북 빌드 에러를 해결합니다.

[FLIZ-205/docs] fix: 스토리북의 user/Calendar 스토리의 잘못된 import 경로 수정

---

.husky/pre-commit
apps/trainer/app/schedule-management/pending-reservations/page.tsx
commitlint.config.cjs
package.json

- husky/pre-commit 워크플로우, root package.json의 lint-staged 스크립트를 작성하여 커밋 전 eslint 오류를 자동으로 수정가능 한 부분은 자동으로 수정(자동 수정 안되는 부분이 있다면 커밋이 안되고 직접 수정해야함)되게 설정하고, 타입 에러가 있을시 커밋이 되지 않도록 작성하였습니다.
- 커밋 내용의 limit 길이가 너무 짧은 것 같아 100 -> 150자로 늘렸습니다.
- 예약 대기 페이지에서 아직 만들어지지 않은 컴포넌트를 import하여 생기는 빌드 오류를 수정하였습니다.

[FLIZ-207/root] chore: husky, lint-staged 워크플로우 및 스크립트 작성

---

apps/user/app/my-page/_components/LogoutButton.tsx
apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx
apps/user/app/my-page/_components/ProfileHeader.tsx
apps/user/app/my-page/_constants/route.ts
apps/user/app/my-page/my-information/_components/MemorizedChangePhoneLink.tsx
apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
apps/user/app/schedule-management/_components/ReservationAdder.tsx
apps/user/app/schedule-management/_constants/route.ts
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
apps/user/components/Providers/FooterProvider.tsx
apps/user/constants/routes.ts

user 서비스에서 사용되는 route 상수를 관리하는 인스턴스를 구현 및 적용했습니다
- tanstack-query에서 사용되는 query key factory 방식에서 착안하여 user 서비스의 route 상수를 계층적으로 관리합니다. 이를 위해 각 경로의 구성 요소 (`/`를 기준으로 분리되는 문자열들)는 private 프로퍼티에 배열로 저장합니다
- 배열로 관리되는 경로를 실제로 사용할 때 다시 `/`로 join된 문자열을 받아야 하기 때문에 경로별로 getter를 정의하여 url 문자열을 만들어주는 로직을 주입했습니다
- 프로젝트 전역에서 ROUTES 인스턴스가 여러 개 생성되는 것을 방지하기 위해 싱글턴 패턴을 사용했습니다
기존 user의 각 경로에서 사용되던 _constants/route.ts 파일은 모두 제거했으며, 새로 정의한 RouteInstance로 교체했습니다

[FLIZ-211/user] feat: 유저 서비스 라우트 상수 정의

---

apps/trainer/app/schedule-management/_components/MemberProfileCard/index.tsx
apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx
apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx
apps/trainer/app/schedule-management/fixed-reservation/_components/SelectTimeRouteButton.tsx
apps/trainer/app/schedule-management/pending-reservations/page.tsx
apps/trainer/app/sns-verification/_components/ResultStep.tsx
apps/trainer/constants/route.ts

트레이너 도메인의 경로를 `_constants` 폴더 내부에 정의하였습니다.
라우팅을 계층적으로 관리할 수 있도록 설계하였으며, routeParams/searchParams를 하드코딩하지 않고 주입할 수 있습니다.
다만, 매번 경로가 새로 생성될때마다 개발자가 직접 RouteInstance에 경로를 직접 추가해주어야 합니다. 해당 사항에 대해서는 좀 더 개선책이 있는지 찾아볼 예정입니다.
route.ts에 삭제하지 않은 주석은 혹시 제가 이번 Task에서 Route 관련 메소드를 사용하고 있는 곳에 RouteInstance를 적용하지 않은 곳이 있을 수 있을 것 같아 남겨둔 것으로, 해당 PR이 머지되기 직전 제거할 예정입니다.
RouteInstance가 계층적으로 잘 관리되고 있는지 체크해주시면 감사하겠습니다.

[FLIZ-212/trainer] chore: 트레이너 도메인 RouteInstance 정의

---

docs/storybook/.eslintrc.js
docs/storybook/package.json
docs/storybook/stories/trainer/Calendar.stories.tsx
docs/storybook/stories/trainer/ScheduleBottomSheet.stories.tsx
docs/storybook/stories/trainer/TimeOption.stories.tsx

- 트레이너 도메인에서 컴포넌트의 위치 변경에 따라 스토리북에서 잘못된 경로로 import 하던 것을 올바른 경로로 수정하였습니다.
- eslint가 스토리북 내에 위치한 tsconfig.json을 참조할 수 있도록 parserOptions를 설정하였습니다.
- eslintrc의 확장자가 `.js`로 되어있어 esm 방식으로 동작하지 못하던 에러를 docs/package.json의 type 프로퍼티를 제거하여 해결하였습니다.

[FLIZ-214/docs] fix: 스토리북 빌드 에러 해결

---

apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx
apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/ApproveButton.tsx
apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/MemberCardList.tsx
apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
apps/trainer/app/schedule-management/pending-reservations/_utils/formatContinuousTimes.ts
apps/trainer/app/schedule-management/pending-reservations/page.tsx
apps/trainer/constants/Day.ts
apps/trainer/services/types/reservations.dto.ts
apps/trainer/services/types/userManagement.dto.ts
packages/core/src/api/types/common.ts
packages/ui/src/components/FunnelSteps/WorkoutScheduleStep.tsx
packages/ui/src/components/WorkoutForm.tsx

기존 트레이너 도메인 예약 관리 페이지를 구현하면서 누락된 예약 대기자 확인 페이지를 구현하였습니다.
- 아직 API는 붙히지 않은 상태로 UI만 구현된 상태입니다. API가 필요한 부분은 TODO 주석을 남겨두었습니다.
- `PreferredWorkout` 타입에 누락된 프로퍼티를 추가하면서 용재님이 구현해주신 `WorkoutForm`, `WorkoutScheduleStep` 컴포넌트의 Props 타입에 Omit을 추가하여 추가된 `workoutScheduleId` 프로퍼티를 제거하도록 수정하였습니다.
- 기능 테스트를 위해 Mock 데이터를 컴포넌트내에 작성해두었습니다. 추후 API를 붙이면 제거할 예정입니다.

[FLIZ-215/trainer] feat: 트레이너 도메인의 예약 대기자를 확인하고 예약을 승인할 수 있는 페이지 구현

---

apps/trainer/app/my-page/my-information/edit-verificated-phone/_components/PhoneVerificationContainer.tsx
apps/user/app/my-page/page.tsx
apps/user/app/notification/_components/NotificationContainer.tsx
apps/user/app/notification/_components/NotificationList.tsx
apps/user/app/register/_components/RegisterFunnel.tsx
apps/user/app/sns-verification/page.tsx
apps/user/constants/routes.ts
apps/user/middleware.ts
apps/user/queries/auth.ts
apps/user/services/auth.ts
apps/user/services/types/auth.dto.ts
apps/user/services/types/myInformation.dto.ts
packages/core/src/api/types/common.ts
packages/ui/src/components/PhoneVerification/index.tsx

user 서비스 휴대폰 인증 로직을 구현했습니다
흐름은 다음과 같습니다 :
1. /login : 소셜 로그인 버튼 클릭 (현재 카카오만 가능) 
2. /sns-verification 으로 redirection
3. /sns-verification 페이지 마운트 시 [이메일 인증 토큰 발급 API] 호출, 응답으로 받은 verificationToken을 휴대폰 인증 로직 모듈 (PhoneVerification 컴포넌트)로 주입
4. 인증 메세지 보내기 버튼 클릭 시 메세지 앱을 열어 verificationToken을 문자 내용으로 담은 문자 생성 + [유저 상태 polling API] 5초마다 호출하여 유저 인증 상태 조회
5. 사용자가 문자를 전송하면 서버에서 유저 인증 상태를 REQUIRED_REGISTER 로 변경, polling 중이던 API 응답으로 REQUIRED_REGISTER 값을 확인하면 /register 로 이동
6. /register 페이지에서 회원 정보 입력 및 회원 가입 진행 (기존 PhoneStep 제거)

[FLIZ-216/user] feat: 휴대폰 인증 로직 구현

---

apps/user/app/register/_components/RegisterFunnel.tsx
apps/user/app/register/_components/ResultStep.tsx
apps/user/app/register/_hooks/useFCMToken.ts
apps/user/app/register/_hooks/useSignupForm.ts
apps/user/app/sns-verification/page.tsx
apps/user/components/Providers/index.tsx
apps/user/middleware.ts
apps/user/package.json
apps/user/public/firebase-messaging-sw.js
apps/user/services/notification.ts
apps/user/services/types/notification.dto.ts
packages/ui/src/components/PhoneVerification/index.tsx
pnpm-lock.yaml

기존에 부분적으로만 구현되어 있던 로그인 플로우를 완성했습니다. 
추가된 부분은 다음과 같습니다
- fcm 서버로부터 fcm 토큰 발급 및 Fitlink 서버에 발급받은 토큰 등록
- 미들웨어 적용 경로 추가 (root 경로)
- 네트워크 요청 status(axios status) 와 Fitlink 서버 응답 status(요청 성공/실패 status code 및 msg)를 종합하여 요청 상태를 나타내도록 수정
- sns-verification 페이지에서 발생하는 sms 메시지 형식 수정
- 유저 도메인에 tanstack query devtools 추가
- 리팩토링 (비동기 요청 및 fcm 로직은 별도의 커스텀 훅으로 추출했습니다)

[FLIZ-233/user] feat: 유저 도메인 로그인 플로우 완성

---

apps/user/app/register/_components/RegisterFunnel.tsx
apps/user/services/attachment.ts
apps/user/services/types/attachment.dto.ts
packages/core/src/api/types/common.ts
packages/ui/src/components/FunnelSteps/BasicInfoStep.tsx
packages/ui/src/components/ProfileImagePicker.tsx

업데이트된 이미지 파일 업로드 API 정책에 맞게 회원 서비스의 회원가입 단계(register) 중 이미지 파일 업로드 로직 및 API request를 수정했습니다.
- 변경된 API 정책은 다음과 같은 플로우를 요구합니다
1. AWS S3 버킷 업로드용 presignedUrl API 요청 (Attachment > POST 이미지 업로드 url 생성)
2. AWS에서 생성한 presignedUrl로 이미지 파일 업로드 API 요청 (Attachment > PUT 이미지 업로드)
3. 회원 프로필 이미지로 S3에 저장한 이미지 파일 등록 API 요청 (Attachment > POST 유저 프로필 등록)
- API 요청은 번호 순서대로 동기적으로 요청합니다
- 2번 API에서 프로젝트에서 설정한 axios config (authorization, etc.)로 요청 시 요청이 실패합니다. 따라서 default config를 사용하기 위해 정의한 http 객체가 아닌 기본 axios API를 사용했습니다
- 회원가입 API에서 attachmentId가 없어도 요청이 성공합니다 (optional). 따라서 위 이미지 업로드 플로우에서 발생하는 API 에러에 대해서 별도의 UI 또는 navigation 정책을 수립하지 않았습니다.

[FLIZ-242/user] feat: 이미지 파일 업로드 로직 구현

---

apps/trainer/app/register/_components/ResultStep.tsx
apps/trainer/app/register/_hooks/useSignupForm.ts
apps/trainer/types/index.d.ts
apps/user/app/register/_components/ResultStep.tsx
apps/user/app/register/_hooks/useSignupForm.ts
apps/user/types/index.d.ts
packages/core/src/api/core.ts

프로젝트 API 응답은 http 응답 status code를 200대로 설정하고, 올바르지 않은 요청일 경우 status 프로퍼티에 http 응답 status code 값을 전달해주고 있습니다.
API 엔드포인트가 올바르다면 http 응답이 실패하지 않기 때문에 axios layer에서 실패한 요청에 대해 Promise.reject를 반환하지 않습니다.
이를 해결하기 위해 axios reponse interceptor에서 response 안의 status 값을 파싱하여 200 <= status < 300 인 경우 response를 반환하고 그 외의 경우 Promise.reject(new AxiosError(...))를 반환해주고 있습니다.
- axios를 사용하기 때문에 http 요청 중 에러가 발생하면 AxiosError 타입의 에러가 발생합니다. 하지만 TanstackQuery는 Error 타입으로 에러를 사용하여 type inference가 안 되는 불편함이 있습니다. 이를 해결하기 위해 [tanstack 공식문서](https://tanstack.com/query/v5/docs/framework/react/typescript#registering-a-global-error)를 참고하여 global error 타입을 AxiosError로 설정했습니다
- 회원가입 프로세스의 ResultStep에서 응답의 에러 메시지와 status 값에 의존적인 로직이 있어 업데이트된 정책을 반영했습니다.
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 …

[FLIZ-247/core] feat: API 응답 에러 판별 로직 구현

---

apps/trainer/app/api/auth/tokens/route.ts
apps/trainer/app/register/_components/ResultStep.tsx
apps/trainer/services/auth.ts
apps/trainer/services/types/auth.dto.ts

회원가입 API 응답 데이터로 accessToken, refreshToken 쌍이 반환되는데, 이를 쿠키에 저장하기 위한 로직을 구현했습니다
토큰 중 refreshToken은 http-only로 설정해야 하기 때문에 클라이언트에서 쿠키 저장 로직을 만들 수 없었습니다. 그래서 Next Route Handler를 사용하여 토큰 저장 API를 만들어 회원가입 API 성공 시 Route Handler가 설정된 URI로 API 호출을 한번 더 하도록 설계했습니다
회원가입 자체를 RouteHandler를 이용하여 1개의 네트워크 요청으로 처리할까도 고민했지만, 별도의 axios config가 설정된 또 하나의 axiosInstance를 만들어야 한다는 점과, API 반환 데이터 형식을 맞추려고 할 시 로직의 복잡도 때문에 회원가입 API 와 토큰 저장 API를 분리했습니다.

[FLIZ-260/trainer] feat: 회원가입 완료 후 토큰 최신화 로직 추가

---

apps/trainer/components/BottomNavigation.tsx
apps/trainer/components/Providers/FooterProvider.tsx
apps/trainer/constants/route.ts
apps/user/components/BottomNavigation.tsx
apps/user/components/Providers/FooterProvider.tsx

user, trainer 서비스 BottomNavigation에 항목별 라우팅 로직을 추가했습니다.
- Nextjs Link API를 사용하여 각각의 항목을 Link로 설정했습니다.
- FooterProvider의 BottomNavigation 여부 판별 로직에서 string 리터럴 경로를 모두 RouteInstance로 수정했습니다
- 두 서비스에서 BottomNavigation 스타일을 통일했습니다

[FLIZ-264/user, trainer] feat: BottomNavigation 라우팅 로직 추가

---

apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
apps/trainer/app/schedule-management/_components/Calendar/index.tsx
apps/trainer/app/schedule-management/_components/ReservationManagementSheet/index.tsx
apps/trainer/app/schedule-management/_constants/reservationConfig.ts
apps/trainer/app/schedule-management/_libs/CalendarUtils.ts
apps/user/app/notification/page.tsx
apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
apps/user/app/schedule-management/_components/Calendar/WeekCell.tsx
apps/user/app/schedule-management/_components/Calendar/WeekRow.tsx
apps/user/app/schedule-management/_components/Calendar/index.tsx
apps/user/app/schedule-management/_components/ReservationAdder.tsx
apps/user/app/schedule-management/_hooks/mutation/useReservationCancelMutation.ts
apps/user/app/schedule-management/_utils/reservationMerger.ts
apps/user/app/schedule-management/page.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationChangeMutation.ts
apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationRequestMutation.ts
apps/user/app/schedule-management/reservation/[mode]/page.tsx
apps/user/constants/routes.ts
apps/user/middleware.ts
apps/user/queries/myInformation.ts
apps/user/services/myInformation.ts
apps/user/services/reservations.ts
apps/user/services/types/myInformation.dto.ts
apps/user/services/types/reservations.dto.ts
packages/core/src/api/types/common.ts

- 유저 도메인에서 필요한 API를 모두 붙혀놓은 상태이며, 아직 Error 및 fallback에 대한 핸들링은 꼼꼼하게 되어있지 않은 상태입니다.
- 우선 API를 빠르게 붙혀 기능테스트를 하면서 Error/Fallback을 핸들링할 예정입니다.
- 공통 DTO 타입 수정으로 인해 트레이너 도메인 코드에서 타입 에러가 발생하여 임시 수정해 놓았습니다.
- Notification 페이지가 SSG로 분류되어 빌드 타임에 API 요청을 하고 있어, 인증 오류 에러가 나타나 빌드하지 못하고 죽는 이슈가 있었습니다. 우선 **빠른 진행을 위해** `'force-dynamic'`로 SSG가 아닌 SSR로 방식으로 렌더링하도록 임시 해결을 해 놓았고, 엄청 크리티컬 한 건 아니지만 다른 페이지들과 크게 다른점은 없어 보이는데, 해당 페이지가 왜 SSG로 렌더링되는지 Notifiaction 페이지 작업자이신 @yjc2021 님께서 한번 확인 해주시면 감사하겠습니다. 저도 이거 이유가 궁금해서 같이 해결해보아도 좋을 것 같아요 :)

[FLIZ-209/user] feat: 유저 도메인 API 작업

---

apps/user/app/api/auth/reissue-token/route.ts
apps/user/app/apiCore.ts
apps/user/app/my-page/layout.tsx
apps/user/app/notification/layout.tsx
apps/user/app/refresh-session/loading.tsx
apps/user/app/refresh-session/page.tsx
apps/user/app/schedule-management/layout.tsx
apps/user/constants/url.ts
apps/user/middleware.ts
apps/user/middleware/handlers/handleProtectedRoute.ts
apps/user/middleware/handlers/handleTokenFromUrl.ts
apps/user/middleware/utils/routeMatchers.ts
apps/user/services/auth.ts
apps/user/services/types/auth.dto.ts
apps/user/utils/auth.ts
apps/user/utils/token.ts

#168 와 동일하게 user 서비스 authorization 로직을 구현했습니다

[FLIZ-263/user] feat: authorization 로직 구현

---

apps/trainer/app/refresh-session/loading.tsx

trainer 프로젝트 빌드 시 발생하는 prerender bug fix를 추가했습니다
refresh-session 페이지가 suspense boundary로 감싸져 있지 않아 발생한 버그를 해결했습니다

[FLIZ-286/trainer] fix: refresh-session 페이지 prerender 에러 해결

---

apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
apps/trainer/app/notification/connect/page.tsx
apps/trainer/app/notification/disconnect/page.tsx
apps/trainer/app/notification/page.tsx
apps/trainer/app/notification/reservation-edit/page.tsx
apps/trainer/app/notification/reservation/page.tsx
apps/trainer/app/notification/session/page.tsx
apps/trainer/components/NotificationAccordion.tsx
apps/trainer/constants/route.ts
apps/trainer/queries/userManagement.ts
packages/core/src/api/types/common.ts
packages/ui/src/components/Header.tsx

- 트레이너 서비스 알림 도메인의 알림 action sheet 및 하위 페이지 API를 연결했습니다
- 데이터 로딩 중 UI 처리를 위해 Suspense를 사용했습니다
- 알림 사이드 바의 routing 로직을 추가했습니다

[FLIZ-285/trainer] feat: 트레이너 알림 action sheet 및 하위 페이지 API 연결

---

apps/trainer/constants/url.ts
apps/user/app/login/_components/LoginButton/index.tsx
apps/user/constants/url.ts

Oauth 로그인 후 서버에서 redirection 경로를 알 수 있도록 기존 로그인 링크에 query string을 추가하는 작업을 진행했습니다
- user 및 trainer 서비스 환경 변수가 추가되었습니다. 로컬 프로젝트에 NEXT_PUBLIC_BASE_URL변수 추가 부탁드립니다

[FLIZ-305/user] fix: 로그인 링크 redirection 경로 버그 해결

---

apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
apps/trainer/app/schedule-management/_components/Calendar/WeekRow.tsx
apps/trainer/app/schedule-management/fixed-reservation/_components/SelectTimeRouteButton.tsx
apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/indext.tsx
apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/page.tsx
packages/ui/src/components/DayOfWeekPicker/Context.tsx
packages/ui/src/components/DayOfWeekPicker/context.tsx
packages/ui/src/components/DayOfWeekPicker/index.tsx
packages/ui/src/hooks/useDayOfWeekPickerContext.ts

- 트레이너의 PT 가능 일정에 따라 요일 및 시간이 필터링되어 페이지에 동적으로 나타나게 됩니다.
- 트레이너의 PT 가능 일정에 따라 스케줄에 동적으로 반영되도록 구현하였습니다.

[FLIZ-308/trainer] feat: 고정 예약 시 요일, 및 시간을 트레이너가 PT 가능한 일정에 맞게 표기되도록 구현

---

apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
apps/user/app/schedule-management/_components/Calendar/index.tsx
apps/user/app/schedule-management/_hooks/mutation/useReservationCancelMutation.ts
apps/user/app/schedule-management/_libs/checkReservationIsFuture.ts
apps/user/app/schedule-management/_utils/reservationMerger.ts
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationChangeMutation.ts
apps/user/app/schedule-management/reservation/[mode]/page.tsx

- Mutation 성공/실패에 대한 핸들링
- 기존에 요청 성공시 보여주던 바텀 시트를 isSuccess로 핸들링
- 유저가 예약 요청시 해당 요일에 예약 변경 요청, 예약 확정, 예약 대기가 걸려있을 경우 추가 요청 X
- 고정 예약 바텀시트 열리지 않는 버그 해결
- 선택한 예약 정보가 과거 예약이라면 바텀시트가 열리지 않도록 수정

[FLIZ-318/user] refactor: 유저 도메인 mutation 요청 고도화 및 사용성 개선

---

apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
apps/trainer/app/notification/page.tsx

trainer 서비스 notification 페이지에서 사용되는 mutation의 onSuccess 콜백에 query invalidation 로직을 추가했습니다

[FLIZ-320/trainer] feat: notification 도메인 mutation 성공 후 쿼리 invalidation 추가

---

apps/trainer/app/register/_components/RegisterFunnel.tsx
apps/user/app/register/_components/RegisterFunnel.tsx

회원가입 > 유저 프로필 등록 단계에서 사용되지 않는 API를 호출하면서 API 실패 에러가 발생하여 attachmentId를 정상적으로 반환하지 않는 버그가 존재했습니다. 해당 API를 user / trainer 서비스에서 제거하여 userProfileImage가 등록되지 않던 버그를 해결했습니다

[FLIZ-301/root] fix: register 단계에서 userProfileImage 등록 API 오류 해결

---

apps/trainer/app/schedule-management/_utils/reservationMerger.ts

- 예약 대기를 2개 이상의 시간으로 걸었음에도 하나의 예약으로 취급되는 에러 수정

[FLIZ-325/trainer] fix: 예약 데이터가 2개 이상일 경우 서로 다른 데이터로 취급하여 예약 데이터를 나타내도록 유틸 함수 수정

---

apps/trainer/components/BottomNavigation.tsx
apps/trainer/components/Providers/FooterProvider.tsx

trainer 서비스에서 pathname이 완전히 일치하지 않더라도 base 경로로 시작하는 경우 true로 판별하도록 수 있도록 Footer 필요 여부 로직을 수정했습니다
pathname이 완전히 일치하지 않더라도 base 경로로 시작하는 경우 true로 판별하도록 Footer Link 중 현재 path에 해당하는 Link 판별 로직을 수정했습니다.

[FLIZ-331/trainer] fix: 알림 종류별 subpage에 footer 없는 버그 fix

---

apps/trainer/app/my-page/_components/MyPagePending.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleApplyAtStep/index.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
apps/trainer/app/my-page/edit-workout-schedule/_hooks/useAddScheduleMutation.ts
apps/trainer/app/my-page/edit-workout-schedule/_hooks/useDeleteScheduleMutation.ts
apps/user/app/my-page/_components/MyPagePending.tsx
apps/user/app/my-page/connect-trainer/_components/InputOTP/index.tsx
apps/user/app/my-page/connect-trainer/_hooks/useRequestConnectTrainer.ts
apps/user/app/my-page/edit-workout-schedules/_components/EditPreferenceTimeContainer.tsx
apps/user/app/my-page/edit-workout-schedules/_hooks/useEditPreferenceTimeMutation.ts
apps/user/app/my-page/my-trainer-information/_components/TrainerUnlinkItem.tsx
apps/user/app/my-page/my-trainer-information/_hooks/useUnlinkTrainerMutation.ts
packages/ui/src/components/InputOTP.tsx

* 기존 마이페이지에서 사용하던 useMutation()을 customHook으로 변환하였습니다.
* 마이페이지 post 요청 시, pending UI를 구현하여 pending 상태 시 보여줄 컴포넌트를 적용하였습니다.
* 유저와 트레이너의 상위 error.tsx에서 reset()만 호출 시, 캐싱된 데이터가 있는 경우 api 호출이 안 되는 것을 확인하고 캐싱 무효화를 위한 router.refresh()를 추가하였습니다.

[FLIZ-334] feat: 마이페이지 useMutation() 훅으로 처리 및

---

apps/trainer/app/schedule-management/_components/ReservationManagementSheet/index.tsx
apps/trainer/app/schedule-management/_constants/reservationConfig.ts
packages/core/src/api/types/common.ts

- 확정된 예약을 취소할 경우 해당 예약의 상태가 예약 취소 거절 상태로 변경되게 되는데, 이에 대한 타입이 없어 누락된 타입을 추가하고 이 타입에 대한 대응을 통해 예약 취소 거절 Status에 대한 대응을 통해 이슈를 해결하였습니다.
- 예약 취소 거절 상태를 예약 확정 상태로 컨버팅 하였습니다.

[FLIZ-341/trainer]  fix: 예약 취소 거절 후, 캘린더 페이지에 들어가니, TypeError가 나타나며 캘린더 페이지가 죽는 이슈 해결

---

apps/trainer/app/my-page/_components/DeleteScheduleBottomSheet.tsx
apps/trainer/app/my-page/_components/EditScheduleBottomSheet.tsx
apps/trainer/app/my-page/_components/MyDayOffContainer.tsx
apps/trainer/app/my-page/_components/ScheduleInformation.tsx
apps/trainer/app/my-page/_components/Skeleton/MyPTHistorySkeleton.tsx
apps/trainer/app/my-page/_components/Skeleton/index.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleApplyAtStep/index.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
apps/trainer/app/my-page/edit-workout-schedule/_hooks/useDeleteScheduleMutation.ts
apps/trainer/app/my-page/page.tsx
apps/trainer/components/PTSchedule.tsx

* 트레이너의 마이페이지에서 변경 예정 시간을 제거할 수 있는 기능을 구현하였습니다.
* 기존 PT 변경 시간에 대하여 null값으로 들어오던 시간값은 시작값 기본 00시 끝값 23시로 넣어 처리하였습니다.
* PT 변경 시간 UI에 대하여 버튼이 보이지 않던 버그를 수정하였습니다.
* 트레이너 마이페이지 Suspense를 api호출 컴포넌트별로 분리하였습니다.

[FLIZ-340] feat: 트레이너 마이페이지 변경 예정시간 제거 기능 구현

---

apps/trainer/app/error.tsx
apps/user/app/error.tsx
apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
packages/ui/src/components/InputOTP.tsx

* 모바일  inputOTP 설정 시, 키보드 타입을 텍스트로 변경
* 에러 페이지 버튼 클릭 시, 강제 재로딩

[FLIZ-347] fix: InputOTP 키보드 타입 변경

---

apps/trainer/app/error.tsx
apps/trainer/app/schedule-management/_components/Calendar/WeekRow.tsx
apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
apps/user/app/error.tsx

- 트레이너/유저 도메인에서 에러 체킹을 위한 콘솔로그 추가(캘린더, 에러.tsx, 예약대기 페이지)

[FLIZ-345/trainer] : 트레이너/유저 도메인에서 에러 체킹을 위한 콘솔로그 추가

---

apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
apps/trainer/app/schedule-management/_utils/reservationMerger.ts

- 캘린더 타임블록 UI 변경 수정
- 예약 현황 데이터에서 최근 데이터가 과거 데이터를 OverWrite 할 수 있도록 컨버팅 함수 수정

[FLIZ-372/trainer] refactor: 캘린더 타임블록 UI 변경 수정, 예약 현황 데이터에서 최근 데이터가 과거 데이터를 OverWrite 할 수 있도록 컨버팅 함수 수정

---

apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
apps/trainer/types/navigator.d.ts
apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
apps/user/types/navigator.d.ts
packages/ui/src/components/ProfileItem.tsx
packages/ui/src/components/PushPermissionSwitch.tsx
packages/ui/src/types/navigator.d.ts
packages/ui/src/utils/getEnvironment.ts

회원, 트레이너 서비스 마이페이지에 알림 설정 권한을 설정/해제 하는 기능을 추가했습니다
브라우저 알림 권한 설정은 Notification.requestPermission 함수로 진행하는데 Notification.permission === 'default' (설정하기 전 상태)에서만 정상적으로 실행됩니다. 한번 설정된 후에는 사용자가 직접 브라우저 또는 앱 시스템 환경 설정에서 권한을 수정해야 합니다. 해당 내용은 Notification.permission !== 'default' 인 상황에서 switch를 수정하려고 시도할 때 팝업으로 표시됩니다.
- 브라우저 내장 API인 Navigator과 Notification에 의존하기 때문에 별다른 처리 없이 로직을 설계할 시 서버 사이드에서 두 API에 접근을 시도하여 에러가 발생합니다. ( 'use client'는 "렌더링 시점"을 클라이언트로 보내지만, JS 코드 자체는 Node.js 서버에서 빌드/분석 시점에 실행될 수도 있습니다). 따라서 hydration이 정상적으로 이뤄지기 위해 브라우저 API 사용 부분은 default 값으로 초기에 설정하고, 컴포넌트 마운트 시 브라우저 API에 접근하도록 useEffect로 설계했습니다
- iOS에서 모바일 pwa를 판단할 때 window.navigator.standalone을 사용한다고 하여 Navigator 타입을 확장했습니다
- keyof typeof ProfileItemVariants 타입이 string인 불편함을 해결하기 위해 satisfies 를 활용하여 type을 수정했습니다
- …

[FLIZ-370/root] feat: 마이페이지에 푸시 알림 허용 스위치 추가

---

apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
apps/trainer/app/schedule-management/_components/Calendar/index.tsx
apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx
apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_hooks/mutations/useFixReservationChangeMutation.ts
apps/trainer/app/schedule-management/page.tsx

- 캘린더에서 고정 예약 타임 블록을 선택하여 고정 에약 변경 Mode가 활성화되고, 캘린더의 특정 타임 블록을 선택해 고정 에약 변경이 가능합니다.
- 고정 예약 변경 Mode가 되면 캘린더에 border가 나타나고, 상단에 "고정 예약 비활성화" 버튼이 나타나 해당 버튼을 클릭하면 변경 모드가 해제되고, 데스크탑에서는 esc 키를 입력하면 버튼 클릭과 동일한 기능을 할 수 있습니다.
- 아래 스크린샷과 플로우를 설정 한 이유는, 기존의 고정 예약 페이지를 재활용하기에는 날짜를 마음대로 설정할 수 없다는 리스크가 있었습니다.
- 고정 예약 변경은 트레이너가 직접 설정하는 것으로 정책상 트레이너에게는 예약에 관련하여 날짜 기간에 대한 제한이 없습니다. 따라서 캘린더에서 직접 타임 블럭을 선택하여 변경하는 방식이 보다 자유롭게 고정 예약을 변경할 수 있도록 구현해주었습니다.
- 추가로 고정 예약 변경 시 예약 현황 데이터 Query를 Invalidate 해주었습니다.

[FLIZ-377/trainer] feat: 트레이너 도메인 고정 예약 변경 기능 구현

---

apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/index.tsx
apps/trainer/app/schedule-management/_components/MemberListContainer/MemberCardList.tsx
apps/trainer/app/schedule-management/_components/MemberListContainer/index.tsx
apps/trainer/hooks/useIntersectionObserver.ts
apps/trainer/queries/userManagement.ts

- 무한 스크롤 기능이 UI상 트레이너 도메인에만 존재하여 해당 도메인에만 기능을 구현하였습니다.
- intercationObserver의 useEffect 의존성 배열에 핸들러를 추가하여, 상위 핸들러가 재할당될때마다 콜백 함수가 재실행되도록 하여 무한 스크롤이 제대로 이루어지지 않는 이슈를 해결하였습니다.

[FLIZ-379/root] feat: 트레이너 도메인 무한 스크롤 기능 구현

---

apps/trainer/public/manifest.json
apps/user/public/manifest.json

- 양쪽 도메인 PWA 색상을 bg-primary 색상으로 변경하여 모바일에서 스크롤을 해도 이질감이 느껴지지 않도록 수정하였습니다.

[FLIZ-381/style] style: PWA 배경색상 bg-background-primary 색상으로 변경

---

apps/user/app/schedule-management/_components/Calendar/index.tsx
apps/user/app/schedule-management/_components/ReservationAdder.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
apps/user/constants/routes.ts

- 캘린더에서 선택한 날짜가 `예약 가능한 기간 정책(2주)`에 해당하면 예약 페이지에 선택한 날짜를 전달하여 캘린더에서 선택한 날짜가 예약 페이지에서도 `Focus` 되도록 기능을 구현하였습니다.

[FLIZ-373/user] feat: 유저 도메인 캘린더에서 선택한 날짜가 예약 페이지로 그대로 전달되는 기능 추가

---

apps/trainer/app/notification/_components/SessionSetterSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
apps/trainer/components/MutationStatusSheet.tsx
packages/ui/src/components/PhoneVerification/PhoneVerificationGuide.tsx
packages/ui/src/components/PhoneVerification/PhoneVerificationImage.tsx
packages/ui/src/components/PhoneVerification/PhoneVerificationNotice.tsx
packages/ui/src/components/PhoneVerification/VerificationInfoDialog.tsx
packages/ui/src/components/PhoneVerification/index.tsx
packages/ui/src/utils/copyToClipboard.ts

안드로이드 환경에서 회원가입/휴대폰 인증 단계를 진행 할 때, 기기의 메신저 앱에 자동으로 주소 및 메시지 내용이 입력되는 기능이 지원되지 않는 버그가 존재했습니다.
해당 버그의 이유는 안드로이드 환경에서 sms:URI를 클릭하면 먼저 브라우저가 URL을 검증하기 때문입니다. 안드로이드 검증 기준이 IOS보다 엄격하며 주소로 전화번호만 허용합니다.
메일로 인증 메시지를 전달해야 하는 서비스 상황 상, 자동으로 메시지 주소 및 내용을 입력해주는 기능은 안드로이드에서 지원할 수 없으며, 대안으로 인증 메시지를 클립보드에 복사한 뒤, 메신저 앱을 실행하도록 구현했습니다
추가로 클립보드가 지원이 안 될 경우, 사용자가 수동으로 인증 메시지를 복사할 수 있도록 [인증 메시지 확인] 버튼을 만들었습니다. 해당 버튼 클릭 시, 인증 메시지 내용이 있는 Dialog가 나타납니다

[FLIZ-368/ui] fix: 안드로이드 환경에서 휴대폰 인증 메시지 전송 지원

---

packages/ui/src/components/PhoneVerification/index.tsx

안드로이드 환경에서 PhoneVerification 단계 action 버튼 클릭 시 메시지 content를 복사하고 메신저 앱으로 전환했었습니다. 연락처 및 인증 메시지 content 복사 기능이 action button click handler 때문에 클립보드 복사 내용이 overwrite되어서 click handler에서 클립 보드 복사 기능을 제거했습니다

[FLIZ-391/ui] fix: 안드로이드 환경 PhoneVerification 버그 fix

---

apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx
apps/trainer/app/schedule-management/reservation/page.tsx
apps/trainer/components/Providers/index.tsx
apps/user/components/Providers/index.tsx

- 기존에는 방어 로직이 없어 같은 날에 같은 회원이 여러번 수업 예약을 할 수 있었습니다.
- 현재는 방어 로직을 넣어 트레이너가 직접 예약 기능으로 같은 날짜에 같은 회원의 예약을 2번 이상 할 수 없도록 정책을 반영하였습니다.
- 2번 이상 예약을 시도하게되면 토스트 에러메시지가 상단에 나타납니다.
- 서버에서 내려주는 에러메시지를 토스트 메시지에 반영하였습니다.
- 용재님께서 토스트 라이브러리를 다른 라이브러리로 교체 작업을 진행중이신 걸로 알고있는데, 라이브러리 변경시 해당 코드가 머지되면 루트 provider에 설정된 토스트 메시지 말고도, 토스트 메시지가 작성된 부분들도 같이 수정해주시면 감사하겠습니다 :)

[FLIZ-394/trainer] feat: 트레이너가 직접 예약시 같은 날짜에 같은 회원이 두 번 이상 수업 예약이 진행될 수 없다는 정책 반영

---

apps/trainer/app/notification/_components/NotificationItemContainer.tsx
apps/trainer/app/notification/_components/NotificationItemFallback.tsx
apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
apps/trainer/app/notification/_components/SheetRenderer/index.tsx
apps/trainer/app/notification/_utils/notificationParser.ts
apps/trainer/app/notification/_utils/parseKoreanDateString.ts
apps/trainer/app/notification/_utils/parser.ts
apps/trainer/app/notification/page.tsx
apps/trainer/app/notification/reservation-cancel/page.tsx
apps/trainer/app/notification/reservation-change/page.tsx
apps/trainer/app/notification/session/page.tsx
apps/user/app/notification/_components/NotificationContainer.tsx
apps/user/app/notification/_components/NotificationItemContainer.tsx
apps/user/app/notification/_utils/notificationParser.ts
packages/ui/src/components/NotificationItem/IconThumbnail.tsx
packages/ui/src/components/NotificationItem/NotificationContent.tsx
packages/ui/src/components/NotificationItem/NotificationItem.tsx

알림 Item ui 및 로직 버그를 해결했습니다
- Icon 찌그러짐 버그
- 알림 메시지 내용 중 `날짜` 데이터 표시 안 되는 버그
- 서버에서 내려주는 알림 메시지 데이터 `\n` 기준 파싱 안 되는 버그
- 예약 취소 Sheet 취소 사유 UI 없는 버그
- NotificationItemFallback 내용과 실제 NotificationItem 내용 불일치 버그
- 트레이너 알림 중 예약 요청 알림 click하여  /pending-reservations로 redirect 시 Invalid Date 버그

[FLIZ-389/root] fix: 알림 item bug fix

---

apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
apps/trainer/app/register/_hooks/useRegisterFcmToken.ts
apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
apps/user/app/register/_hooks/useRegisterFcmToken.ts
packages/ui/src/components/Button.tsx
packages/ui/src/components/PushPermissionSwitch.tsx
packages/ui/src/hooks/usePushPermissionSwitch.ts

기존에는 마이페이지>푸시 알림 스위치 활성화 시 브라우저 Notification 설정만 허용했습니다.
하지만 회원가입 과정에서 오류가 발생했거나, 여러 기기에서 계정을 공유하면 FCM 연동 API를 호출한 적이 없어 알림이 수신되지 않을 수도 있습니다. 
이를 해결하기 위해 스위치 활성화 시, 브라우저 Notification을 허용하고, FCM 연동 API를 호출하도록 수정했습니다. 
또한, Notification이 허용된 경우, 도움말 UI가 나타나며, 해당 UI를 클릭하면 Sheet가 열립니다. 
이 시트에서는 브라우저 알림을 허용한 사용자들에게 푸시 알림 연동 API를 재호출할 수 있는 방안을 제공합니다.

[FLIZ-399/root] feat: 푸시 알림 스위치에 FCM 연동 로직 추가

---

apps/user/app/notification/layout.tsx
apps/user/app/notification/page.tsx

@5unwan/user 앱 notification 페이지 진입 시 다음과 같은 에러가 발생했습니다
```
Uncaught Error: Could not find the module "/Users/yongjae/Documents/projects/5unwan-fe/packages/ui/src/components/Header.tsx#default#Title" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```
해당 에러 발생 이유는 다음과 같습니다.
RSC (notification/layout.tsx)에서 Client component (Header.tsx)를 import 하여 Client component의 internal component (Header.Title)를 사용하려고 했습니다.
**RSC가 Client Component를 import할 수 있는 조건은 다음과 같습니다**
- Client Component의 default export를 import + render할 수 있습니다
- Client Component의 내부 컴포넌트 (property), nested export, named export를 사용할 수 없습니다
> 참고
> 1. 빌드 시 번들러는 Server build / Client build를 분리해서 만듭니다
> 2. 그리고 빌드 중에 Next.js는 server / client manifest (모듈 이름 및 export를 명세하는 JSON 파일)를 만듭니다. 이때, …

[FLIZ-404/user] fix: 알림 페이지 Header SSR bugfix

---

apps/trainer/app/schedule-management/_components/Calendar/DayColumn.tsx
apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
apps/trainer/app/schedule-management/_components/Calendar/TimeColumn.tsx
apps/trainer/app/schedule-management/_components/Calendar/index.tsx

- 트레이너 캘린더 타임 블록내 텍스트가 길어지면 말줄임 표시(...)
- 트레이너 캘린더의 시간 텍스트 00:00 -> 00으로 변경
요런 느낌(IPhone SE 버전)

[FLIZ-408/trainer] style: 트레이너 캘린더 시간 및 타임 블록내 텍스트 스타일 수정

---

apps/trainer/app/schedule-management/_components/Calendar/TimeColumn.tsx
apps/trainer/app/schedule-management/_components/Calendar/index.tsx

[FLIZ-415/trainer] style: 트레이너 도메인 캘린더 시간 컬럼 UI 깨짐 해결

---

apps/trainer/components/BottomNavigation.tsx
apps/trainer/components/Providers/FooterProvider.tsx
apps/user/components/BottomNavigation.tsx
apps/user/components/Providers/FooterProvider.tsx

기존 사용자가 바텀네비게이션을 통하여 탭을 이동할 때, 반응 없이 딜레이 되다가 페이지가 변경된 후 페이지 변경 및 바텀네비게이션 활성화된 탭 색상을 즉시 변경되도록 구현하였습니다.
구현은 state 사용하여 바텀시트와 페이지가 반응하도록 구현하였습니다.
1. 레퍼런스는 토스를 참고하였으며, 탭을 누르면 화면은 지워지고 탭은 이동합니다. (반응을 통하여 사용자 경험을 향상)
2. 빈 화면에서 페이지가 불러와지며 스켈레톤이 그려짐
3. 페이지 로딩
2번에서 로딩화면을 부탁하셨으나, 잠깐의 이동에서도 로딩되는 화면이 잠깐보여 오히려 사용자에게 좀 불쾌한 느낌을 주어 로딩페이지는 과감히 삭제하였습니다.
테스트가 필요하시다면
FooterProvider.tsx 파일에
```typescript
<div className="flex h-full w-full items-center justify-center">
<Spinner />
</div>
```
위 코드를 삽입하여 바텀시트를 이동해보시면 확인 가능합니다.

[FLIZ-413/root] feat: BottomNavigation 클릭 시, 즉시 반응하도록 구현

---

apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx

주말에 나온 작업 리스트에 트레이너 연동 상태를 보여줄 시, 트레이너의 이름을 보여주면 좋을 거 같다는 의견에 트레이너 이름이 표시되도록 수정하였습니다.

[FLIZ-437/user] feat: 트레이너 연동상태 표시에 트레이너 이름 추가

---

apps/trainer/app/member-management/_components/MemberManagementContainer/PtRemainingCountEditSheet.tsx
apps/trainer/app/member-management/_components/MemberManagementContainer/PtTotalCountEditSheet.tsx
apps/trainer/components/Providers/index.tsx
apps/trainer/constants/pathname.ts
apps/trainer/hoc/WithBottomSheetStepper.tsx
apps/trainer/services/types/auth.dto.ts
apps/user/components/Providers/index.tsx
apps/user/constants/pathname.ts
apps/user/services/types/auth.dto.ts

- 트레이너 도메인의 회원 세션 수정 바텀시트의 Stepper 관련 QA를 적용하였습니다 -> 총 세션은 잔여 세션보다 적을 수 없다 / 잔여 세션은 총 세션보다 많을 수 없다 / 잔여세션 0 이하로 지정 X
- 양쪽 도메인 유저 role을 체크하여 url 확인 후 올바른 도메인으로 리다이렉팅

[FLIZ-436/root] fix: 트레이너 도메인 세션 수정 바텀시트 QA, 트레이너/회원 도메인 유저 role에 따른 리다이렉트 QA

---

apps/trainer/components/Providers/index.tsx
apps/user/components/Providers/index.tsx
packages/ui/src/components/PhoneVerification/index.tsx

휴대폰 인증 페이지에서 버튼이 최하단에 위치하지 않던 스타일링 이슈를 해결 하였습니다
컨테이너 역할 div에 flex flex-1을 주어 버튼을 제외한 안내하는 영역은 자동으로 남은 부분을 사이즈로 가지도록 수정하였습니다.

[FLIZ-439/root] style: flex-1 값을 통하여 버튼 제외한 인증 안내 영역 전체 페이지 사이즈 할당

---

apps/trainer/app/sns-verification/page.tsx
apps/user/app/sns-verification/page.tsx
packages/ui/src/components/PhoneVerification/index.tsx

인증문자 전송 버튼 클릭 후 대기 UI의 부재로 UX가 저하되는 문제를 보완하기 위한 작업입니다.
문자 전송 버튼을 누르더라도 실제 문자 전송 여부는 알 수 없기 때문에 버튼 클릭 시 영원히 버튼을 disabled 처리하는 것보다, 일정 시간(10초)마다 user verification status가 업데이트되지 않았다면 button disabled 처리와 대기 UI를 보여주고 해당 시간이 지난 후에는 다시 버튼을 활성화하여 재전송을 할 수 있도록 처리했습니다

[FLIZ-425/root] feat: 회원가입 문자 인증 단계에서 문자 전송 시 interval 로직 추가

---

apps/trainer/components/Providers/index.tsx
apps/user/components/Providers/index.tsx

- 회원 도메인에서 가입 한 회원 유저가 회원 계정으로 트레이너 도메인에서 로그인 -> dev.trainer OR trainer(prod)로 리다이렉트
- 트레이너 도메인에서 가입한 트레이너 유저가 트레이너 계정으로 회원 도메인에서 로그인 ->  dev.user OR user(prod)로 리다이렉트
- 양 도메인 인증 정보 불러올 수 없을 시 로그인 페이지로 리다이렉트

[FLIZ-441/root] fix: 가입한 도메인에 맞지 않은 계정으로 로그인하거나, 인증에 실패할 경우 리다이렉트 로직 구현

---

apps/trainer/app/my-page/my-information/page.tsx
apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
packages/ui/src/components/ProfileItem.tsx

- ProfileItem 고정 width로 인한 모바일 환경에서 페이지 overflow bugfix
- 트레이너 세션 알림 PT완료/불참석 처리 mutation 성공 시에만 다음 Sheet 표시
- 트레이너 마이페이지 > 내 정보 페이지 padding 조정 

[FLIZ-447/root] fix: HOTFIX

---

apps/trainer/public/firebase-messaging-sw.js
apps/user/public/firebase-messaging-sw.js

ServiceWorkerGlobalScope의 notificationclick 이벤트를 사용하여 푸시 알림 클릭 이벤트핸들러 로직을 추가했습니다
클릭시 알림이 지워지고, 1. 서비스가 열려있다면 focus, 2. 열려있는 핏링크 서비스가 없다면 /notification 경로로 엽니다

[FLIZ-449/root] feat: background 푸시알림 클릭핸들러 추가

---

packages/ui/src/components/Header.tsx

Header의 subHeader가 의도와 다르게 viewport에 sticky하게 위치하지 않는 버그를 해결했습니다

[FLIZ-450/ui] fix: subHeader sticky position 유지를 위해 레이아웃 수정

---

apps/trainer/app/notification/_components/NotificationContainer.tsx
apps/trainer/app/notification/_components/NotificationItemContainer.tsx
apps/trainer/app/notification/_components/NotificationPageClient.tsx
apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
apps/trainer/app/notification/_components/NotificationsPerPage.tsx
apps/trainer/app/notification/_components/NotificationsPerPageFallback.tsx
apps/trainer/app/notification/_components/SheetRenderer/index.tsx
apps/trainer/app/notification/connect/_components/ConnectContainer.tsx
apps/trainer/app/notification/connect/_components/NotificationPageClient.tsx
apps/trainer/app/notification/connect/page.tsx
apps/trainer/app/notification/disconnect/_components/DisconnectContainer.tsx
apps/trainer/app/notification/disconnect/_components/NotificationPageClient.tsx
apps/trainer/app/notification/disconnect/page.tsx
apps/trainer/app/notification/page.tsx
apps/trainer/app/notification/reservation-cancel/_components/NotificationPageClient.tsx
apps/trainer/app/notification/reservation-cancel/_components/ReservationCancelContainer.tsx
apps/trainer/app/notification/reservation-cancel/page.tsx
apps/trainer/app/notification/reservation-change/_components/NotificationPageClient.tsx
apps/trainer/app/notification/reservation-change/_components/ReservationChangeContainer.tsx
apps/trainer/app/notification/reservation-change/page.tsx
apps/trainer/app/notification/reservation/_components/NotificationPageClient.tsx
apps/trainer/app/notification/reservation/_components/ReservationContainer.tsx
apps/trainer/app/notification/reservation/page.tsx
apps/trainer/app/notification/session/_components/NotificationPageClient.tsx
apps/trainer/app/notification/session/_components/SessionContainer.tsx
apps/trainer/app/notification/session/page.tsx
packages/core/src/api/types/common.ts

- 트레이너 서비스에서 '세션' type 알림 종류가 '세션 곧 종료' / '세션 완료' 알림으로 분기되었습니다. 따라서 기존 '세션' 알림 클릭 시 UX를 '세션 곧 종료' + '세션 완료' 알림 으로 분리하는 작업을 진행했습니다. 
'세션 곧 종료' 알림 클릭 시 'schedule-management' 페이지로 redirect합니다
'세션 완료' 알림 클릭 시 별도의 UX 없이 알림 읽음 API만 호출합니다
*** 기존 '세션' 처리 BottomSheet는 사용하지 않습니다. 업데이트된 알림 API 구조상, 알림 정보에서 session 처리 API 호출에 필요한 데이터를 받아올 수 없게 되었습니다. 따라서 일단 schedule-management 페이지로 redirect 하고, 사용자가 직업 time cell을 클릭해서 처리하는 UX로 수정했습니다.
- 알림 페이지 및 하위 페이지 네트워크 waterfall을 최적화하였습니다
tanstack query의 prefetchQuery를 활용하여 notification detail API를 미리 호출하도록 수정했습니다. 또한 상위 Suspense로 인해 notification detail API가 serial 하게 fetch되던 문제를 해결하기 위해 일부 Suspense를 제거하고 RSC를 활용했습니다.
기존 워터폴의 diagram입니다
```
page.tsx (client)
│
├── NotificationContainer (client)
│   └── Suspense (page suspends here)
│       ├── …
```

[FLIZ-452/trainer] feat: 알림 도메인 API 업데이트 및 페이지 네트워크 최적화

---

apps/trainer/app/my-page/_components/LogoutButton.tsx
apps/trainer/app/my-page/_components/MyPageHeader.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/ScheduleChangeResultSheet.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleFunnel.tsx
apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx
apps/user/app/my-page/_components/LogoutButton.tsx
apps/user/app/my-page/_components/ProfileHeader.tsx
apps/user/app/my-page/connect-trainer/_components/InputOTP/index.tsx
apps/user/app/my-page/edit-workout-schedules/_components/BottomSheet/SuccessEditPreferenceTimeBottomSheet.tsx
packages/core/src/api/core.ts

* 각 페이지 특성에 맞는 라우팅 함수로 변경하였습니다.
앱에서 라우팅이 이루어질 때, 뒤로가기를 통해 다시 돌아갈 수 없어야 할 페이지에 대해 router의 `replace()`를 사용하여 이전 페이지에 접근을 방지하였습니다.
* `@toss/useFunnel`에 경우 funnel 작업에 대한 back() 기능 제공을 위하여 push로 history를 쌓아놓는 방식 이후, next router에는 몇 단계 돌리는 기능이 없어 onNext()를 추가하여 funnel.history 함수를 통하여 Trainer 희망 수업 시간 변경 funnel의 3단계(변경 -> 날짜선택 -> 확인) 만큼의 -3값을 `.go()` 를 사용하여 희망 시간 변경 페이지의 재진입을 방지하였습니다.
[@toss/useFunnel history 문서](https://use-funnel.slash.page/ko/docs/use-funnel#funnelhistory)

[FLIZ-453/root] refactor: 페이지 router 특징에 따른 라우팅 함수 (push, replace) 적용

---

packages/core/src/api/core.ts

기존 SSR에서도 토큰이 없는 경우  `window`를 사용할 수 있는 경우를 방지하기 위하여 조건값을 추가하였습니다.
❓ 왜 기존 코드에서 조건만 더했는가
[StackOveflow](https://stackoverflow.com/questions/77872949/next-js-14-0-4-browser-back-button-allows-access-to-protected-routes-after-log) 및 블로그를 확인해본 결과 
axios 사용처 혹은 middleware에서 토큰을 검사 후 NextResponse.redirect()를 통하여  페이지를 이동시켜주는 것을 확인하였습니다.
좀 더 안전하게 진입을 막기 위해서 클라이언트 컴포넌트에서 (로그아웃 후 뒤로가기를 하였을 때 마이페이지에 진입할 수 밖에 없는 상황이라 MyPage에서 토큰을 검사하려하였으나 Next useRouter 이벤트 사용)
클라이언트 컴포넌트에서 검사하고자한다면, access-token만을 검사할 수 있는데, access-token이 없는 상태라고 login 페이지로 사용자를 보내주는 것은 동작에 맞지 않는다고 생각하였습니다.(리프레시가 있으면 access-token이 만료됐거나 없을 때 재발급할 수 있기 때문에)
Next 서버에서 검사하면 보일러 플레이트가 발생할 것 같으며, 뒤로가기 후,  core 파일의 axios가 실행되는 것을 확인하고 core.ts 단에서 방지하고자 하였습니다.
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 …

[FLIZ-462] feat: axios 토큰 검사 시,  SSR에서의 window 참조 방지를 위한 조건 설정

---

packages/ui/src/components/Header.tsx

기존 개인 워크스페이스에 있던 문서를 [새로운 워크스페이스](https://www.notion.so/Fit-Link-245764b4d45580da9230e07a9e3b374e?source=copy_link)를 생성하여 가이드 내용을 옮겨두었으며, 사용자 가이드에 앱으로 이용하는 방법에 대한 내용을 추가하였습니다.
앱 우측 상단에 유저 가이드 페이지로 이동할 수 있는 기능을 구현하였습니다.
데스크탑 클릭 시 새로운 탭을, 앱에서 클릭 시 앱을 벗어나지 않고 새로운 윈도우에서 가이드 페이지가 나타나도록 하였습니다.
Header가 공통으로 사용되고 있어 연결 링크는 가이드 페이지의 부모페이지인 앱 서비스 인사 페이지로 연결하였습니다.

[FLIZ-461/root] feat: 로고 우측에 사용자 가이드 페이지 링크 연결

---

apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
apps/trainer/app/schedule-management/_components/Calendar/WeekRow.tsx
apps/trainer/app/schedule-management/_components/Calendar/index.tsx
apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationChangeRequestBottomSheet.tsx
apps/trainer/app/schedule-management/_components/ReservationManagementSheet/index.tsx
apps/trainer/app/schedule-management/_constants/reservationConfig.ts
apps/user/app/schedule-management/_components/Calendar/index.tsx
apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
packages/core/src/api/types/common.ts

- 트레이너/회원 예약 현황 API DTO 변경
- 트레이너 휴무일, PT 가능시간, 예약 현황 데이터 mount 될때마다 refetch
- 트레이너 도메인 캘린더의 타임 블록에 예약 변경 요청 상태 나타나지 않는 버그 수정
- 예약 페이지 mount시 데이터 refetch
- 예약 변경 요청 상태 타임 블록 클릭시 나타나는 바텀시트 구현

[FLIZ-456/root] fix: 예약 변경 승인 타임블록 이슈 수정
