Fit-Links/FitLink-FE

package.json
Root 환경에서 각 하위 패키지인 `trainer`, `user` 패키지를 빌드 또는 개발 서버 실행을 보다 편리하게 실행 시킬 수 있도록 Root package.json에 script를 작성하였습니다.
각 명령어 실행 방법은 아래와 같습니다.
```
pnpm run dev:trainer
pnpm run dev:user
pnpm run build:trainer
pnpm run build:user`
```
close #5
=> [#5] chore: 루트의 하위 패키지 trainer, user 각 패키지의 빌드 및 개발 서버 실행을 실행 시킬 수 있는 script 작성

docs/storybook/stories/FontSize.mdx, package.json, packages/config-tailwind/tailwind.config.ts, turbo.json
- Typography의 경우 어떠한 동적인 테마 전환이나 런타임에서 값이 변경될 가능성이 없고, 고정된 값으로 판단되어 css 변수로 만들지 않고, 직접 `tailwind.config.ts`에 작성하였습니다.
- 정의한 Typography 토큰을 스토리(mdx)로 작성하여 문서화 하였으며 내용은 아래 이미지와 같습니다
- 문서 작성은 스토리북 공식문서를 참고하였습니다 -> [스토리북 Typography 작성 문서](https://storybook.js.org/docs/api/doc-blocks/doc-block-typeset)
close #10
=> [#10/config-tailwind] feat: 시스템 Typography 토큰화 적용

packages/config-tailwind/tailwind.config.ts, packages/config-tailwind/variables.css
디자인 색상 정책이 변경되어 @5unwan/tailwind-config의 css 변수 및 tailwind 토큰을 수정했습니다
background
- sub4 : hsl(0 0 47)
- sub5 : hsl(0 0 100)
close #20
=> [#20/config-tailwind] style: 색상 토큰 업데이트 

.github/pull_request_template.md
프로젝트를 JIRA와 연동하면서 변경된 컨벤션에 맞게 PR 템플릿을 수정했습니다.
- PR 제목 컨벤션을 수정했습니다
- 깃헙 이슈 연동 부분을 제거했습니다
=> [FLIZ-12/root] chore: PR 템플릿 수정

pnpm-lock.yaml
=> [FLIZ-27/root] fix: pnpm-lock 버전 오류 hotfix

docs/storybook/package.json, docs/storybook/stories/Accordion.stories.tsx, packages/config-tailwind/tailwind.config.ts, packages/ui/package.json, packages/ui/src/components/Accordion.tsx, packages/ui/src/components/Accordion/context.tsx, packages/ui/src/components/Accordion/index.tsx, packages/ui/src/hooks/useAccordionContext.ts, pnpm-lock.yaml
Radix primitives를 사용하여 구현하였으며 내부적으로 커스텀이 추가되었습니다.
- `icon` props를 통해서 Accordion의 각 타이틀에 아이콘을 주입 할 수 있습니다.
- `icon`이 주입되면 AccordionContent에서 icon의 크기를 계산하여 icon의 크기만큼 좌측으로 padding을 적용합니다.
- Accordion 컴포넌트 내에서 Icon의 크기를 공유하기 위해 contextAPI를 사용하였습니다.
- 아래 사진과 같이 알림 갯수를 나타낼때에는 `content` 또는 `trigger``children`에 직접 구현하여 주입 할 수 있도록 유연하게 설계하였습니다.
아래는 사용 예시입니다.
```ts
<div className="bg-background-sub2 w-72 p-6">
<Accordion type={args.type} className="w-full">
<AccordionItem value="item-1">
<AccordionTrigger icon={<HeartHandshake />}>
<span>회원 연동</span>
<span className="bg-background-sub4 w-7 rounded-full text-center">5</span>
</AccordionTrigger>
<AccordionContent>
<span>연동 승인</span>
<span className="bg-background-sub4 w-7 rounded-full text-center">3</span>
</AccordionContent>
<AccordionContent> …
```
=> [FILZ-17/ui] feat: Accordion 공통 컴포넌트 구현

docs/storybook/stories/Text.stories.tsx, packages/ui/src/components/Text.tsx
컴포넌트에 사용될 `Text`를  합성(컴파운드) 컴포넌트로 구현해보았습니다.
_(해당 컴포넌트는 회의를 거쳐서 사용 여부가 결정될 것으로 보입니다.)_
* 기본 접근은 `Title1` 타입을 가집니다.
* 토큰 이름을 사용하여 작성하였으며, 합성 컴포넌트로 아래와 같이 사용할 수 있습니다.
```typescript
return (
<div>
<Text.Title1>Title1</Text.Title1>
<Text.Title2>Title2</Text.Title2>
<Text.Headlinel>Headline1</Text.Headline1>
<Text.Subhead1>Subhead1</Text.Subhead1>
<Text.Subhead2>Subhead2</Text.Subhead2>
<Text.Body1>Body1</Text.Body1>
<Text.Body2>Body2</Text.Body2>
<Text.Body3>Body3</Text.Body3>
<Text.Body4>Body4</Text.Body4>
</div>
)
```
* 합성 컴포넌트로서 따로 속성값을 변경하여 컴포넌트를 변경할 수 없어서 컴포넌트 개별적으로 Story로 나타내었습니다.
* 스토리북 구조와 텍스트 컴포넌트의 구조가 어떠한지 봐주시면 감사하겠습니다.
* 텍스트 컴포넌트 구현에 대해 이견이 있으시다면 말씀해주시면 감사하겠습니다.
=> [PRIZ 36/ui] feat. Text 공통 컴포넌트 구현

.github/workflows/deploy.yml, build.sh
개인 계정에 프로젝트 레포지토리를 fork한 뒤, 개인 vercel로 fork 를 배포하는 스크립트를 작성했습니다. Github Actions를 활용했으며 사용되는 secret 변수는 AUTO_ACTIONS 및 EMAIL 입니다. 두 secret 모두 팀 레포지토리 secrets로 설정 완료했습니다.
=> [FLIZ-30/root] chore: 개인 vercel 자동 배포 설정

packages/config-tailwind/tailwind.config.ts
tailwind.config.ts에 animation 속성이 중복 선언된 ts 에러를 해결했습니다
=> [FLIZ-59/config-tailwind] fix: tailwind.config.ts 에러 해결

packages/config-tailwind/tailwind.config.ts
- 변경했던 `Typography` 토큰을 이전 스펙으로 다시 롤백하였습니다. 변경된 토큰으로 인해 전체 스타일링이 모두 깨져서 롤백 하였으며, 새롭게 추가된 `title-3`, `body-5`, `body-6`의 `line-height`는 다시 변경될 가능성이 있습니다.
=> [FLIZ-79/config-tailwind] chore:  Typography 토큰 롤백 및 새롭운 Typography 토큰 추가

apps/trainer/.eslintrc.json, apps/user/.eslintrc.json
스토리북 배포에서 발생하는 lint 에러를 해결하기 위해 next 프로젝트의 eslint 정책을 수정했습니다. 코드가 푸시되어 배포 log를 확인하여 효과가 없으면 다시 revert하겠습니다
=> [FLIZ-128/config-eslint] fix: next 프로젝트 린팅 정책 수정

apps/trainer/tailwind.config.ts
유저 도메인의 tailwind.config content의 불필요한 파일 스캔을 수정하여 성능 저하를 방지하였습니다.
=> [FLIZ-177/user] fix: 유저 도메인의 tailwind.config content의 불필요한 파일 스캔 수정

turbo.json
turborepo의 lint 및 deploy 스크립트를 수정했습니다
=> [FLIZ-179/root] chore: turborepo 스크립트 수정

packages/config-eslint/next.js
배포 시 next 프로젝트에서 발생하는 prettier lint 에러를 해결하기 위해 config-eslint/next.js 에 eslint-config-prettier를 추가했습니다
=>  [FLIZ-180/config-eslint] chore: next.js config에 eslint-config-prettier 추가

docs/storybook/README.md
=> [FLIZ-181/docs] rename: storybook 배포 링크 url 수정

build.sh
배포를 위해 cicd 액션 실행시 개인 리포지토리로 숨김 파일은 제거되고 clone이 되는 에러를 수정하였습니다.
=> [FLIZ-196/fix] root:  cicd 액션 실행시 개인 리포지토리로 숨김 파일은 제거되고 clone 되는 에러 수정

.github/workflows/deploy.yml, build.sh
build.sh, deploy.yml 수정했던 로직들을 모두 rollback 하였습니다.
=> [FLIZ-198/root] fix:  build.sh, deploy.yml 수정했던 로직들 모두 rollback

.github/workflows/deploy_MaSeungHyun.yml
조직 레포를 포크하여 Vercel에 연동하여 자동배포 기능을 설정하였습니다.
토큰을 발급받아 팀 레포 설정에
`MSH_AUTO_ACTIONS`
`MSH_EMAIL`
값을 추가하여, deploy 파일을 따로 작성하여 환경 변수값을 변경하였습니다.
=> [FLIZ-230/root] ci: 포크 레포 커밋 싱크 워크플로우 작성

packages/ui/src/components/FunnelSteps/TrainerScheduleStep.tsx
트레이너 수업 시간 설정 단계에서 사용자가 설정한 [시작 시간] / [종료 시간]을 관리하는 데이터 형식이 API 제출 시 전달해야 하는 형식과 달라 API 요청이 실패하는 문제가 존재했습니다.
이를 해결하기 위해 API 요청 직전에, 수업 시간 데이터를 순회하여 API 제출용 형식으로 변환하는 로직을 추가하여 문제를 해결했습니다.
=> [FLIZ-250/trainer] fix: PT 시간 설정 형식 오류 해결

apps/user/app/my-page/_components/MyPageContainer.tsx, apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx, apps/user/app/my-page/my-information/page.tsx, apps/user/app/my-page/my-trainer-information/_components/MyTrainerInformationContainer.tsx, apps/user/app/my-page/my-trainer-information/page.tsx, apps/user/app/my-page/page.tsx
prefetchQuery() 사용 중, 서버에서 토큰으로 유저 정보를 가져올 때, 토큰을 가져오지 못 하여
`401`에러로 `UnAuthorized`라는 인증되지 않은 버그를 뱉어내어 `useQuery()`로 대체하여 버그를 수정하였습니다.
```shell
$ pnpm run build
```
를 통해 빌드를 확인하였으며 오류 없이 통과하였습니다.
=> [FLIZ-257] fix. 빌드 에러 해결

apps/user/app/api/auth/tokens/route.ts, apps/user/app/register/_components/ResultStep.tsx, apps/user/services/auth.ts, apps/user/services/types/auth.dto.ts
#154 와 동일하게 user 서비스에 토큰 최신화 로직을 추가했습니다
=> [FLIZ-261/user] feat: 회원가입 완료 후 토큰 최신화 로직 추가

apps/trainer/app/member-management/[memberId]/_components/MemberProfile.tsx, apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx, apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/index.tsx, apps/trainer/app/member-management/[memberId]/page.tsx, apps/trainer/app/schedule-management/_components/Calendar/DayColumn.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx, apps/trainer/app/schedule-management/fixed-reservation/_components/SelectTimeRouteButton.tsx, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/Header.tsx, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/FixedReservationAdderButton.tsx, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_hooks/mutations/useFixReservationChangeMutation.ts, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_utils/fixReservationUtils.ts, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/page.tsx, apps/trainer/constants/route.ts, apps/trainer/queries/userManagement.ts, apps/trainer/services/reservations.ts, apps/trainer/services/types/reservations.dto.ts, apps/trainer/services/types/userManagement.dto.ts, apps/trainer/services/userManagement.ts, packages/core/src/api/types/common.ts, packages/ui/src/components/PTHistoryItem.tsx, packages/ui/src/components/PTPreference.tsx, packages/ui/src/utils/makeWeekSchedule.ts
- 회원관리 상세 페이지 구현
- 회원관리 상세 페이지에서 고정 예약 기능 구현
backlog
- 고정 예약 변경 기능 구현
- 고정 예약 해제 기능 구현
- infiniteQuery 사용 위해 intersection Observer 적용
=> [FLIZ -282/trainer] feat: 트레이너 도메인 회원 관리 상세 페이지 기능 구현

apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx, apps/trainer/app/member-management/_components/MemberManagementContainer/MemberProfileList.tsx, apps/trainer/app/member-management/_components/MemberManagementContainer/PtRemainingCountEditSheet.tsx, apps/trainer/app/member-management/_components/MemberManagementContainer/PtTotalCountEditSheet.tsx, apps/trainer/app/my-page/_components/EditScheduleBottomSheet.tsx, apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/ScheduleChangeResultSheet.tsx, apps/trainer/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx, apps/trainer/app/notification/_components/SessionSetterSheet.tsx, apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx, apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx, apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx, apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationNotAllowedCancelSheet.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx, apps/trainer/app/schedule-management/_components/ScheduleBottomSheet.tsx, apps/trainer/app/schedule-management/_components/TimeOptionList.tsx, apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/FixedReservationAdderButton.tsx, apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/ApproveButton.tsx, apps/user/app/my-page/_components/BottomSheet/EditPreferredScheduleBottomSheet.tsx, apps/user/app/my-page/edit-workout-schedules/_components/BottomSheet/SuccessEditPreferenceTimeBottomSheet.tsx, apps/user/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx, apps/user/app/my-page/my-trainer-information/_components/BottomSheet/UnlinkAlarmSheet.tsx, apps/user/app/schedule-management/_components/BottomSheet/RequestSuccessSheet.tsx, apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx, apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
user, trainer 서비스의 Sheet에서 발생하는 slide animation 위치 버그를 해결했습니다
=> [FLIZ-292/ui] fix: Sheet slide animation 버그 해결

apps/trainer/app/notification/_components/NotificationContainer.tsx, apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx, apps/trainer/app/notification/_components/SheetRenderer/index.tsx, apps/trainer/app/notification/page.tsx, apps/trainer/app/notification/reservation/page.tsx, apps/trainer/services/notification.ts, apps/trainer/services/reservations.ts, apps/trainer/services/userManagement.ts, packages/core/src/api/types/common.ts, packages/ui/src/components/NotificationItem/IconThumbnail.tsx
=> [FLIZ-300/trainer] fix: 버그 해결

apps/trainer/app/login/_components/LoginButton/index.tsx, apps/trainer/app/schedule-management/_components/Calendar/DayColumn.tsx
[FLIZ-304/trainer] f: pr 제목ix
/
=> FLIZ-304 fix: 로그인 uri 버그 fix

apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx, apps/trainer/components/Providers/index.tsx, apps/trainer/package.json, pnpm-lock.yaml
- 트레이너 도메인 최상단에서 mutation 성공/실패에 대한 메시지를 react-toastify를 통해 구현
=> [FLIZ-309/trainer] feat: 트레이너 도메인 최상단에서 mutation 성공/실패 메시지 띄우는 기능 구현(react-toastify)

apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx, apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
- 트레이너 도메인에서 예약 불가 설정 시, 기존에 예약 불가 설정 타임 블록을 클릭했을 때 나타나야 하는 바텀시트가 나타나는 버그 해결
- 지난 수업 타임 블록 클릭 시 유저의 상세 정보가 카드에 제대로 나타나지 않는 버그 해결
=> [FLIZ-311/trainer] fix: 트레이너 도메인 예약 불가 설정 바텀시트 버그 해결

apps/user/next.config.mjs
@yjc2021 님의 작업과 마찬가지로  user쪽에서 또한 api profileURL을 안전하게 불러오고 최적화 할 수 있도록 next.config.mjs  파일을 수정하였습니다.
remotePatterns 배열 안에 이미지 호스팅을 허용할 도메인 목록을 명시하여 지정된 도메인에서의 이미지만 사용할 수 있도록 제한하였습니다.
=> [FLIZ-324] feat: 외부 도메인 이미지 가져오기 최적화

apps/trainer/app/schedule-management/page.tsx, apps/trainer/components/Fallback/LoadingFallback.tsx, apps/user/app/layout.tsx, apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx, apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx, apps/user/app/schedule-management/_components/Calendar/index.tsx, apps/user/app/schedule-management/_components/Fallback/ConnectionFallback.tsx, apps/user/app/schedule-management/page.tsx, apps/user/app/schedule-management/reservation/[mode]/_components/Fallback/PtTimeSelectorFallback.tsx, apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx, apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx, apps/user/components/Fallback/LoadingFallback.tsx, apps/user/components/Providers/FooterProvider.tsx, packages/config-tailwind/.eslintrc.js, packages/config-tailwind/tailwind.config.ts, packages/ui/src/components/PhoneVerification/index.tsx
- 트레이너 캘린더/예약 페이지에 Loading Fallback UI를 적용하였습니다.
=> [FLIZ-329/user] feat: 트레이너 캘린더/예약 페이지 Loading Fallback UI 적용

apps/trainer/app/member-management/[memberId]/_components/MemberProfile.tsx, apps/trainer/app/schedule-management/_components/Fallback/FixedReservationListFallback.tsx, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/FixedReservationAdderButton.tsx, apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_utils/fixReservationUtils.ts, apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx, apps/trainer/app/schedule-management/pending-reservations/page.tsx, apps/user/app/schedule-management/_components/Calendar/Header.tsx, apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationChangeMutation.ts
- 트레이너 도메인 고정 예약 validation 함수 수정 및 , 회원/트레이너 도메인에서 사용되지 않는 UI 제거
=> [FLIZ-343/trainer] fix: 트레이너 도메인 고정 예약 validation 함수 수정 및 , 회원/트레이너 도메인에서 사용되지 않는 UI 제거

apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx, apps/trainer/package.json, pnpm-lock.yaml
- 예약 대기 상세 조회에서 발생하는 서버와 클라이언트의 시간차 에러 수정
=> [FLIZ-344/trainer] fix: 예약 대기 상세 조회에서 발생하는 서버와 클라이언트의 시간차 에러 수정

apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
=> [FLIZ-345/trainer] fix: 예약 대기 상세 조회 시간차 오류 재수정

packages/ui/src/components/FunnelSteps/TrainerScheduleStep.tsx
=> [FLIZ-350/ui] fix: 서버 시간대 대응

apps/trainer/components/Providers/index.tsx, apps/user/components/Providers/index.tsx
=> [FLIZ-351/root] fix: tanstack default 설정 수정

apps/trainer/components/Providers/FooterProvider.tsx, apps/user/components/Providers/FooterProvider.tsx
앱 상단에 적당한 패딩을 추가하였습니다. 로고를 넣자는 의견도 있어 로고를 넣어보았는데 이쁘지 아니하여 우선 마진만을 넣어둔 상태입니다.
=> FLIZ-352 feat: 전체 레이아웃에 상단에 마진 추가

apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
=> FLIZ-359 fix: 예약 대기 API 상세 조회 시간 + 9

apps/trainer/services/reservations.ts, apps/trainer/services/types/userManagement.dto.ts, apps/trainer/services/userManagement.ts
- 회원 연동 해제, 예약 변경 요청 승인 API EndPoint 수정
=> [FLIZ-362/trainer] fix: 회원 연동 해제, 예약 변경 요청 승인 API EndPoint 수정

packages/ui/src/lib/DateController.ts
DateController.toAbsolute 반환 데이터 형식이 API 요청 데이터 형식과 불일치하여 발생하던 API 요청 버그를 해결했습니다
=> [FLIZ-346/trainer] fix: 예약 변경 승인 API 요청 형식 fix

apps/trainer/components/FunnelSteps/TrainerScheduleStep.tsx
트레이너 회원가입 / 수업 시간 설정 단계에서 휴무일 여부 상태를 true로 변경했습니다
=> [FLIZ-380/trainer] feat: 회원가입/수업 시간 설정 단계에서 휴무일 여부 기본값을 true로 수정

apps/trainer/app/schedule-management/_components/TimeOptionList.tsx, apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx, apps/trainer/app/schedule-management/reservation/page.tsx
- 사파리에서 발생한 크로스 브라우징 이슈를 해결하였습니다.
=> [FLIZ-416/trainer] fix: 예약 페이지 사파리 date 생성자 이슈 해결

apps/trainer/hooks/useFcmListener.ts, apps/trainer/public/firebase-messaging-sw.js, apps/user/hooks/useFcmListener.ts, apps/user/public/firebase-messaging-sw.js
=> [FLIZ-426/root] fix: FCM 데이터 파싱 로직 수정

apps/trainer/app/member-management/_components/MemberManagementContainer/PtRemainingCountEditSheet.tsx, apps/trainer/app/member-management/_components/MemberManagementContainer/PtTotalCountEditSheet.tsx, apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx, apps/trainer/app/schedule-management/_components/Calendar/WeekRow.tsx, apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx, apps/trainer/app/schedule-management/_utils/reservationMerger.ts, apps/trainer/queries/reservation.ts
- 캘린더 예약 대기 인원 불일치
- 회원관리 > 회원 세션 수정 -> 회원의 이름 불일치
=> [FLIZ-435/trainer] fix: 트레이너 도메인 캘린더/회원가입 QA 해결

apps/trainer/components/Providers/index.tsx, apps/user/components/Providers/index.tsx
=> FLIZ-442 fix: 유저 role 확인 로직 주석 처리

apps/trainer/middleware/handlers/handleRedirectByUserRole.ts, apps/user/middleware/handlers/handleRedirectByUserRole.ts
- 미들웨어에서 잘못 체크한 도메인 url 로직을 수정하였습니다.
=> [FLIZ-445/root] fix: 양 도메인 Role 체크 후 잘못된 경로 check 로직 수정

apps/trainer/middleware.ts, apps/trainer/middleware/handlers/handleTokenFromUrl.ts, apps/user/middleware.ts, apps/user/middleware/handlers/handleTokenFromUrl.ts
유저 롤 체크하는 로직을 로그인 후 리다이렉트 하는 곳으로 이동했습니다.
=> FLIZ-446 refactor: 유저 롤 체크 로직 이동

apps/trainer/app/loading.tsx, apps/user/app/loading.tsx
각 app에 최상위 loading.tsx 파일을 추가했습니다
=> [FLIZ-458/root] feat: root loading.tsx 추가

apps/trainer/app/notification/connect/page.tsx, apps/trainer/app/notification/disconnect/page.tsx, apps/trainer/app/notification/page.tsx, apps/trainer/app/notification/reservation-cancel/page.tsx, apps/trainer/app/notification/reservation-change/page.tsx, apps/trainer/app/notification/reservation/page.tsx, apps/trainer/app/notification/session/page.tsx
- 트레이너 알림페이지 빌드 이슈를 동적 라우트를 활용해 해결하였습니다.
=> FLIZ-464 fix: 트레이너 도메인 알림 페이지 빌드 에러 dynamic 라우트로 해결

apps/trainer/app/member-management/_components/MemberManagementContainer/PtCountEditSheet.tsx, apps/trainer/components/UserPermissionGuard.tsx, apps/user/app/schedule-management/_utils/timeCellGenerator.ts, apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx, apps/user/components/UserPermissionGuard.tsx
- 트레이너/회원 sns-verification 단계 permission Guard 제거
- user - 예약 변경 페이지 original 예약 데이터 timeCell ui 다르게 반영
- trainer - 세션관리 바텀시트 ui 수정, 회원간 세션이 공유되는 이슈 해결
=> [FLIZ-466/root] fix: 3차 QA 적용

.github/workflows/deploy_prod.yml
production 배포 CI/CD 구축 작업을 진행했습니다
=> [FLIZ-468/root] chore: vercel prod 배포 CI/CD 구축

.github/workflows/deploy_prod.yml
=> [FLIZ-470/root] fix: deploy_prod 워크플로우 bug fix

.github/workflows/deploy_prod.yml, .github/workflows/release.yml
=> [FLIZ-472/root] fix: deploy_prod 워크플로우 bug fix 3
